ariatemplates/ariatemplates

- src/aria/widgets/form/TextInput.js
- test/aria/widgets/form/TextareaTest.js
If the data model contains, for example, "&pound" the field should display it as it is. Before this commit the content of the text area would be a pound sign.
> Escape html in @aria:Textarea widget

- src/aria/widgets/form/TextInput.js
- test/aria/widgets/form/textinput/TextInputTestSuite.js
- test/aria/widgets/form/textinput/blurOnDestroy/ClickButtonAfterDestroyTest.js
- test/aria/widgets/form/textinput/blurOnDestroy/ClickButtonAfterDestroyTpl.tpl
- test/aria/widgets/form/textinput/blurOnDestroy/ClickButtonAfterDestroyTplScript.js
In IE, after destroying a TextInput having focus, the focus was not correctly released.
This had an impact on the behaviour of the application.
For example, when clicking on a button after the refresh operation, the click event was not being raised.
> Blur after destroying a TextInput

- .travis.yml
- package.json
- scripts/attester-nophantom.sh
- test/aria/widgets/container/dialog/movable/test5/MovableDialogTestCaseFive.js
- test/attester-nophantom.yml
Some tests were never run locally due to some issues with PhantomJS.
This PR makes `npm test` run those tests with Chrome and Firefox, via Selenium Java Robot.
> fix #1391 run Phantom-unfriendly tests also in Travis

- src/aria/widgets/container/Dialog.js
- test/aria/widgets/container/dialog/DialogTestSuite.js
- test/aria/widgets/container/dialog/closeOrDrag/CloseOrDragTest.js
- test/aria/widgets/container/dialog/closeOrDrag/CloseOrDragTpl.tpl
This PR fixes the following issue: on some browsers, clicking on the close button of the dialog is randomly interpreted as the beginning of a drag/drop operation, preventing the dialog from being closed.
> Dialog widget: clicking on the close button interferes with drag/drop

- src/aria/utils/Dom.js
This fixes a regression on IE 7 and 8 introduced by commit 84ffd08ec7f10a8dcaeb6bad6a8375ae95ad60e4 because aria.core.Browser.isWindowsPhone is not correctly implemented (to be fixed later).
> Removing isWindowsPhone in aria.utils.Dom.getViewportSize

- src/aria/utils/Size.js
- test/aria/widgets/container/dialog/resize/test1/DialogOnResizeTestCase.js
This commit fixes test.aria.widgets.form.autocomplete.popupWidth.AdaptToContentWidthTest on Safari.
> fix AdaptToContentWidthTest on Safari

- test/aria/widgets/container/checkContent/DivTest.js
Fixes test.aria.widgets.container.checkContent.DivTest on Safari (in which scroll bars take no space).
> Fix test.aria.widgets.container.checkContent.DivTest on Safari

- src/aria/jsunit/$RobotSelection.js
- src/aria/jsunit/Robot.js
Sometimes, if the first test to be executed by a browser is a robot test, it can fail with the error "The robot is not available." even if the browser was started with `selenium-java-robot` because `selenium-java-robot` has not yet injected the `SeleniumJavaRobot` object in the page. This PR makes sure we wait up to 2s before raising the error that the robot is not available.
> Allowing the robot not to be available immediately (waits for 2s)

- test/aria/templates/TemplateManagerTest.js
- test/aria/templates/section/asContainer/SectionAsContainerTest.js
This PR fixes a regression introduced in commit f9a167054598fdab57137f9a06cec83d36b6477b for TemplateManagerTest and SectionAsContainerTest on IE 7.
On IE 7, the toString method of an error object returns no information about the error (only the string "[object Error]"). It is necessary to use the description property instead.
This PR depends on the following pull request on noder-js: https://github.com/ariatemplates/noder-js/pull/30
> Failing TemplateManagerTest and SectionAsContainerTest on IE 7

- src/aria/templates/CSSMgr.js
- test/aria/templates/css/CSSTestSuite.js
- test/aria/templates/css/cssMgr/tagReuse/TagReuseTestCase.js
- test/aria/templates/css/cssMgr/tagReuse/TestCss.tpl.css
It is important for an application to decide the order
in which widgets and templates-related css rules
(coming from CSS templates) are inserted in the head tag.
In order to do that, the application can insert tags with the correct id. This commit allows to use existing tags for the css insertion.
> Allow CSSMgr to reuse existing tags

- src/aria/utils/validators/Validator.js
- src/aria/utils/validators/ValidatorMessages.js
- src/aria/utils/validators/ValidatorMessagesCfgBeans.js
- test/aria/utils/validators/Validator.js
This commit provides the possibility to globally set messages for validators.
Validators will show the message with highest priority in this order:
1) Local message
2) Global message
3) Hardcoded default
close #
> feat # validator messages at application level

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/WidgetsRes.js
- src/aria/widgets/controllers/AutoCompleteController.js
- src/aria/widgets/controllers/DateController.js
- src/aria/widgets/controllers/NumberController.js
- src/aria/widgets/controllers/TextDataController.js
- src/aria/widgets/controllers/TimeController.js
- src/aria/widgets/environment/WidgetSettingsCfgBeans.js
- src/aria/widgets/form/TextInput.js
- test/aria/widgets/form/BaseDefaultErrorMessagesTest.js
- test/aria/widgets/form/autocomplete/AutoCompleteTestSuite.js
- test/aria/widgets/form/autocomplete/defaultErrorMessages/DefaultErrorMessagesTest.js
- test/aria/widgets/form/autocomplete/defaultErrorMessages/DefaultErrorMessagesTestTpl.tpl
- test/aria/widgets/form/datefield/DateFieldTestSuite.js
- test/aria/widgets/form/datefield/defaultErrorMessages/DefaultErrorMessagesTest.js
- test/aria/widgets/form/datefield/defaultErrorMessages/DefaultErrorMessagesTestTpl.tpl
- test/aria/widgets/form/numberfield/NumberFieldSuite.js
- test/aria/widgets/form/numberfield/defaultErrorMessages/DefaultErrorMessagesTest.js
- test/aria/widgets/form/numberfield/defaultErrorMessages/DefaultErrorMessagesTestTpl.tpl
- test/aria/widgets/form/timefield/defaultErrorMessages/DefaultErrorMessagesTest.js
- test/aria/widgets/form/timefield/defaultErrorMessages/DefaultErrorMessagesTestTpl.tpl
It is now possible for a user to customize the error messages used by the widgets.
There are 3 levels of error messages specifications, the two firsts being user configuration while the last is the hardcoded default.
This is resolved in this order of precedence:
- local: widget's configuration
- global: application's environment
- hardcoded: widget's resources
> feat Customization of widget's error messages

- src/aria/widgets/WidgetsRes.js
- src/aria/widgets/controllers/TextDataController.js
- test/aria/widgets/form/BaseDefaultErrorMessagesTest.js
- test/aria/widgets/form/autocomplete/defaultErrorMessages/DefaultErrorMessagesTest.js
The implementation code is now cleaner and more documented, as well as for the test. A little bit of redundancy checking has been introduced in the tests just to make sure that if the order of some methods changes or if some are removed or whatever the tests will still work and be comprehensive.
Also fixed a small mistake in AutoComplete's default error messages test.
An unwanted `return` statement was remaining at the end of the `$constructor` of the test. It was not breaking anything regarding our class system implementation, but this remains incorrect.
Added backward compatibility for widget's default error messages customization. The non-backward change concerns the keys used inside a resource file to define the hardcoded fallback for default values.
There is no deprecation message or …
> feat Improved the widget's default error messages customization and added backward compatibility

- src/aria/html/Element.js
- test/aria/html/HTMLTestSuite.js
- test/aria/html/radioButton/listenerAfterDestruction/ListenerCalledAfterDestruction.tpl
- test/aria/html/radioButton/listenerAfterDestruction/ListenerCalledAfterDestructionTest.js
This commit introduces a check on the status of the widget before reacting to data change.
It can happen that the `_notifyDataChange` method is called after the widget destruction.
> fix #1436 Check widget destruction before reacting to data change

- src/aria/utils/Json.js
- test/aria/utils/JsonTest.js
If you inject an object into another setting the merge flag to true, if the objects are identical and contain cyclic references, then the maximum call stack size is exceeded.
> Avoid useless recursion in aria.utils.Json.inject if objects are identical

- src/aria/html/DisabledTrait.js
- test/aria/html/HTMLTestSuite.js
- test/aria/html/radioButton/disabled/DisabledStateTest.js
- test/aria/html/radioButton/disabled/DisabledStateTestTpl.tpl
When two `html:RadioButton`s disabled state is bound to the same non-initialized data model, an error was triggered.
This was due to the fact that when the `initWidget` method of the first one was called, a `setValue` was done on the data model, which triggered some listeners to modify the disabled state of the second one, for which the `initWidget` method had not been called yet, so that property `this._domElt` had not been set yet.
> Disabled state in html:RadioButton widget

- build/grunt-config/config-atpackager-prod.js
- src/aria/atLoader.js
- src/aria/utils/FrameATLoader.js
- test/MainTestSuite.js
- test/aria/atLoader/AtLoaderTest.js
- test/aria/atLoader/atLoader.html
- test/aria/atLoader/atLoader.js
atLoader is used to synchronously load Aria Templates classes that are not included
in the AT package.
It is sufficient to insert the array of classes as the innerHTML of the tag
used to load this script.
All the classes' dependencies have to be added to this array.
No comments or other sintax is allowed in it except for the array itself.
> feat atLoader injector script to load AT packages

- src/aria/utils/overlay/Overlay.js
In IE 7 and 8, `aria.utils.Dom.getStyle(domElt, "borderTopWidth")` can return something like `"medium"`, which was unexpected by the `aria.utils.overlay.Overlay._setInPosition` method, which would then fail with an "Invalid argument" exception (when setting "NaNpx" for the `width` or `height` property of the overlay style).
After 604f33b756e5796dfd43ef5b8f1e8051047309bd, now that an Overlay is created by default for movable dialogs, this problem made several movable dialog tests fail in IE 7 and IE 8, such as:
test.aria.widgets.container.dialog.movable.test1.MovableDialogTestCase
test.aria.widgets.container.dialog.movable.test2.MovableDialogTestCaseTwo
test.aria.widgets.container.dialog.movable.test3.MovableDialogTestCaseThree
test.aria.widgets.container.dialog.movable.test4.MovableDialogT …
> Fixing several movable dialog tests in IE 7 and IE 8

- src/aria/utils/Dom.js
This commit improves the detection of the extra pixels returned by `getBoundingClientRect` in IE 7.
cf http://chunghe.blogspot.fr/2008/03/15-use-getboundingclientrect-if.html
and https://github.com/jquery/jquery/blob/master/src/offset.js#L101-106
> aria.utils.Dom.calculatePosition extra pixels in IE 7

- .gitignore
- src/aria/core/useragent/.gitignore
As `/src/aria/core/useragent/ua-parser.js` was ignored through a `.gitignore` file which had no corresponding `.npmignore` file, the `.gitignore` file was used as the default `.npmignore`, leading to /src/aria/core/useragent/ua-parser.js not being included in the npm package (which makes the yeoman generator `yo ariatemplates` fail, cf http://ariatemplates.com/forum/showthread.php?tid=267).
> Adding /src/aria/core/useragent/ua-parser.js to npm package

- src/aria/popups/Popup.js
- src/aria/popups/PopupManager.js
- src/aria/widgets/form/DropDownTextInput.js
- src/aria/widgets/form/MultiSelect.js
- test/aria/widgets/form/multiselect/MultiselectTestSuite.js
- test/aria/widgets/form/multiselect/popupReposition/MultiSelect.js
- test/aria/widgets/form/multiselect/popupReposition/MultiSelectStyle.tpl.css
- test/aria/widgets/form/multiselect/popupReposition/MultiSelectTpl.tpl
- test/aria/widgets/form/multiselect/popupReposition/MultiSelectTplScript.js
Clicking on a multiselect option often triggers a refresh, which may lead to the multiselect being visually moved. This commit makes sure that, in that case, the popup moves along with the multiselect.
> Repositions the popup of the multiselect when clicking on an option

- src/aria/widgets/form/MultiSelect.js
- test/aria/widgets/form/multiselect/MultiselectTestSuite.js
- test/aria/widgets/form/multiselect/emptyMultiSelect/MultiSelect.js
- test/aria/widgets/form/multiselect/emptyMultiSelect/MultiSelectTpl.tpl
This pull request fixes the following issue: when a `@aria:MultiSelect` widget is empty (i.e. when its `items` property is an empty array) and when clicking on the dropdown icon to open the popup, the widget gets the focused style and keeps it forever (even when the focus is somewhere else).
> Empty multiselect focus issue

- src/aria/core/Browser.js
- src/aria/core/IO.js
- src/aria/utils/Device.js
- test/aria/core/BrowserTest.js
- test/aria/utils/DeviceTest.js
Deprecated methods which log a warning and then call the new implementation don't depend on the ability of the platform to provide property descriptors. I fixed the code according to that statement.
I also did an unrelated typo fix.
> Fixed the setup of the deprecation for aria.utils.Device (and replicated for aria.core.Browser).

- tasks/easypackage/configuration.js
- test/node/gruntTasks.js
Binary files (such as images) were modified by the easypackage grunt task when copied to the destination folder.
This PR fixes this issue.
> easypackage grunt task modified binary files

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/Widget.js
- src/aria/widgets/environment/WidgetSettingsCfgBeans.js
The `waiAria` flag allows to enable or disable accessibility either globally or at each widget level.
> [WAI-ARIA] Adding the waiAria flag for widgets in the AriaLib

- src/aria/utils/Date.js
- test/aria/utils/Date.js
This PR adds support for the `cutYear` option in the case of `interpretFullDateRef` (missing case in #1488).
> cutYear option not used in interpretFullDateRef (cf #1488)

- src/aria/widgets/form/AutoComplete.js
- src/aria/widgets/form/DropDownListTrait.js
- src/aria/widgets/form/TextInput.js
- src/aria/widgets/form/list/CfgBeans.js
- src/aria/widgets/form/list/List.js
- src/aria/widgets/form/list/templates/LCTemplate.tpl
- src/aria/widgets/form/list/templates/ListTemplate.tpl
- test/aria/widgets/WidgetsTestSuite.js
- test/aria/widgets/wai/WaiTestSuite.js
- test/aria/widgets/wai/autoComplete/AutoCompleteBaseTest.js
- test/aria/widgets/wai/autoComplete/AutoCompleteGlobalNonWaiTestCase.js
- test/aria/widgets/wai/autoComplete/AutoCompleteGlobalWaiTestCase.js
- test/aria/widgets/wai/autoComplete/AutoCompleteNonWaiTestCase.js
- test/aria/widgets/wai/autoComplete/AutoCompleteTpl.tpl
- test/aria/widgets/wai/autoComplete/AutoCompleteTplScript.js
- test/aria/widgets/wai/autoComplete/AutoCompleteWaiTestCase.js
- test/aria/widgets/wai/autoComplete/WaiAutoCompleteTestSuite.js
This PR adds the DOM attributes required for the aria:AutoComplete widget to comply with the WAI-ARIA specifications (when the `waiAria` flag is enabled).
It is built on top of #1490
> [WAI-ARIA] aria:AutoComplete widget

- src/aria/core/environment/Environment.js
- src/aria/core/environment/EnvironmentBaseCfgBeans.js
- src/aria/widgets/Widget.js
- src/aria/widgets/environment/WidgetSettingsCfgBeans.js
- test/aria/widgets/wai/autoComplete/AutoCompleteGlobalWaiTestCase.js
- test/aria/widgets/wai/autoComplete/AutoCompleteNonWaiTestCase.js
With this PR, the `waiAria` flag is now inside `appSettings` so that it can be used outside `AriaLib` widgets (e.g. for processing indicator...).
> [WAI-ARIA] Moving waiAria flag to appSettings (instead of widgetSettings)

- src/aria/utils/Beans.js
The `yearBeforeMonth` option was not documented. This PR adds documentation in the bean.
> Adding doc about the yearBeforeMonth option (for aria.utils.Date functions)

- test/aria/widgets/wai/autoComplete/AutoCompleteBaseTest.js
This PR fixes the aria.widgets.wai.autoComplete.* failing tests.
There were random errors due to some checks which could happen before the list widget was fully loaded.
There were also some errors on IE 7 because of the wrong implementation of the partial polyfill for querySelectorAll (also because of the missing hasAttribute method on IE 7).
> aria.widgets.wai.autoComplete.* tests failing

- test/plugins.js
- test/test.htm
This commit adds the "plugin" URL parameter which allows to add any JavaScript file in the test page.
> Allowing JS plugins to be inserted client-side through the ?plugin= syntax

- src/aria/widgets/Icon.js
- src/aria/widgets/form/CheckBox.js
- test/aria/widgets/form/radiobutton/RadioButtonTestSuite.js
- test/aria/widgets/form/radiobutton/multiLine/MultiLineTestCase.js
- test/aria/widgets/form/radiobutton/multiLine/MultiLineTestCaseTpl.tpl
This pull request fixes an issue with the check box and radio button when the label is large enough to wrap over multiple lines: the icon was not centered vertically.
> Radio button and check box icon not centered vertically when the label has multiple lines

- src/aria/utils/Dom.js
- test/aria/utils/DomScrollIntoView.js
- test/aria/utils/UtilsTestSuite.js
- test/attester-nophantom.yml
- test/attester-packaged.yml
aria.utils.Dom.scrollIntoView failed to scroll the document on Chrome when the body had no margin.
> fix aria.utils.Dom.scrollIntoView issue on Chrome

- package.json
- src/aria/core/Browser.js
- src/aria/utils/Dom.js
- test/aria/core/useragent/UseCases.js
This commit adds the new isEdge flag to allow Microsoft Edge to be detected. For this purpose, the version of `ua-parser-js` was updated, which also fixes an invalid name for the Android Browser on some devices, and simplifies the code regarding PhantomJS detection.
Note that this pull request does not include any fix to improve the compatibility of Aria Templates with Microsoft Edge (which will be added in a later PR, if required)
> Browser detection improvements: adding isEdge, fixing issues

- src/aria/popups/Beans.js
- src/aria/popups/Popup.js
- src/aria/popups/PopupManager.js
- src/aria/popups/container/DomElement.js
- src/aria/popups/container/IPopupContainer.js
- src/aria/popups/container/Manager.js
- src/aria/popups/container/Viewport.js
- src/aria/templates/Layout.js
- src/aria/utils/dragdrop/Drag.js
- src/aria/utils/resize/Resize.js
- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Dialog.js
- test/aria/utils/dragdrop/DragDropCSS.tpl.css
- test/aria/widgets/container/ContainerTestSuite.js
- test/aria/widgets/container/dialog/DialogTestSuite.js
- test/aria/widgets/container/dialog/MovableDialogTestSuite.js
- test/aria/widgets/container/dialog/container/BaseDialogContainerTestCase.js
- test/aria/widgets/container/dialog/container/DialogContainer.tpl
- test/aria/widgets/container/dialog/container/DialogContainerScript.js
- test/aria/widgets/container/dialog/container/DialogContainerStyle.tpl.css
- test/aria/widgets/container/dialog/container/DialogContainerTestSuite.js
- test/aria/widgets/container/dialog/container/FocusDialogContainerTestCase.js
- test/aria/widgets/container/dialog/container/HideResizeDialogContainerTestCase.js
- test/aria/widgets/container/dialog/container/MaximizeDialogContainerTestCase.js
- test/aria/widgets/container/dialog/container/MoveDialogContainerTestCase.js
- test/aria/widgets/container/dialog/container/ResizeDialogContainerTestCase.js
- test/attester-nophantom.yml
- test/attester-packaged.yml
This PR adds a new `container` property for the `@aria:Dialog` widget.
If this property is defined, the dialog is inserted as a child of the corresponding DOM element (which must have the `position:relative` or `position: absolute` style), and the dialog can only be moved or resized inside this element. If the dialog is modal, the modal mask is only above the container, and focusing elements outside the container is still possible.
This PR also contains a commit which fixes issues in the Resize/Drag utilities.
> Allowing dialogs to be inside a container

- tasks/easypackage/configuration.js
- test/node/gruntTasks.js
- test/nodeTestResources/testProject/gruntfiles/Gruntfile3.js
This pull request fixes a regression introduced by commit c3e296e18ae8f02ae7cfb0f0a10ec80b5be17a1f.
It also makes sure dependencies declared in templates are correctly detected during packaging.
> fix easypackage failing when templates are not packaged

- src/aria/utils/SynEvents.js
- src/aria/widgets/AriaSkinBeans.js
- src/aria/widgets/action/Link.js
- src/aria/widgets/action/LinkStyle.tpl.css
- test/aria/widgets/action/link/disabled/LinkDisabled.js
- test/aria/widgets/action/link/disabled/LinkDisabledTpl.tpl
- test/aria/widgets/action/link/disabled/LinkDisabledTplScript.js
This commit fixes the following issue: when different `sclass` with different colors for the disabled state are defined for the aria:Link widget, all disabled links were using the same color for the disabled state, regardless of the `sclass` property.
> fix aria:Link disabled color when skin contains multiple `sclass`

- src/aria/widgets/controllers/SelectBoxController.js
- test/aria/widgets/form/selectbox/SelectboxTestSuite.js
- test/aria/widgets/form/selectbox/emptyOption/EmptyOptionTestCase.js
- test/aria/widgets/form/selectbox/emptyOption/EmptyOptionTestCaseTpl.tpl
- test/aria/widgets/form/selectbox/emptyOption/EmptyOptionTestCaseTplScript.js
This pull request fixes the following issue: when a (non-null) value of an aria:SelectBox widget is selected and has an empty label, clicking on the field and immediately leaving it changes the value to null. On IE11 this also happens when clicking on the dropdown button.
> Empty label issue with aria:SelectBox widget

- src/aria/templates/View.js
- src/aria/widgets/CfgBeans.js
- src/aria/widgets/action/SortIndicator.js
- test/aria/widgets/action/ActionTestSuite.js
- test/aria/widgets/action/sortindicator/fixSortKeyGetter/SortIndicatorSortKeyGetterTest.js
- test/aria/widgets/action/sortindicator/fixSortKeyGetter/SortIndicatorSortKeyGetterTestTpl.tpl
- test/aria/widgets/action/sortindicator/fixSortKeyGetter/SortIndicatorSortKeyGetterTestTplScript.js
This PR fixes the following issues with the sortKeyGetter property of the SortIndicator widget:
- it was not possible to use an object with `scope`, `fn` and `args` properties
- it could not be `null`, to disable the automatic sort done by the widget
> Issues with the sortKeyGetter property of the SortIndicator widget

- src/aria/utils/Bridge.js
- test/aria/utils/UtilsTestSuite.js
- test/aria/utils/bridge/BridgeTest.js
- test/aria/utils/bridge/laterRoot/LaterClass-xyz.js
- test/aria/utils/bridge/root/bridgeTest/BridgeCtrl-abcde.js
- test/aria/utils/bridge/root/bridgeTest/BridgeTpl-efghi.tpl
This PR fixes #1074.
Unlike #1075, it links the url map and root map of the popup window to the ones of the parent window, so that if the maps of the parent window are later updated, the popup window benefits from those changes. It also contains a test.
> Bridge url map and root map

- src/aria/Aria.js
- src/aria/core/JsonValidator.js
- src/aria/node.js
- test/aria/AriaTest.js
- test/aria/core/JsonValidatorTest.js
- test/aria/core/io/IOTransportTest.js
- test/aria/ext/filesgenerator/GeneratorTest.js
This PR adds an error in the console in case classpath dependencies are used outside the backward-compatible loader.
The backward-compatible loader is automatically used to load a class when no call to "require" is done in the module being loaded.
However, using both "require" and old-style classpath dependencies in a module can cause issues, because, in CommonJS, a module is considered loaded as soon as its content has been executed, but this is too early if classpath dependencies still have to be loaded. As a consequence, another class can be executed when its dependencies are not all fully loaded.
So this commit helps the developer to detect such issues and to fix them as early as possible.
> Logging error for classpath dependencies outside the old loader

- src/aria/templates/Modifiers.js
- src/aria/widgets/form/list/templates/LCTemplate.tpl
- test/aria/templates/ModifiersTest.js
- test/aria/widgets/form/autocomplete/AutoCompleteTestSuite.js
- test/aria/widgets/form/autocomplete/ampersandSuggestion/AmpersandSuggestion.js
- test/aria/widgets/form/autocomplete/ampersandSuggestion/AmpersandSuggestionTpl.tpl
- test/aria/widgets/form/autocomplete/ampersandSuggestion/AmpersandSuggestionTplScript.js
This PR fixes the following issue: when typing an ampersand in the autocomplete, and if some suggestions match, suggestions are wrongly displayed with '&' replaced by the corresponding '&amp;amp;' entity. Adding another letter afterwards switches back to the correct display, but then the highlighting in the suggestion no longer works (while there is an ampersand in the input).
> Fix wrong display of ampersand in the suggestions of the autocomplete

- src/aria/utils/Date.js
- test/aria/utils/Time.js
- test/aria/widgets/form/timefield/checkValue/TimeField.js
- test/aria/widgets/form/timefield/checkValue/TimeFieldTpl.tpl
Previously there were cases where some alphabetic characters were accepted as valid entries and subsequently transformed into valid times, now all alphabetic characters are illegal unless they are one of the following special cases:
- a m
- p m
- h
- m
> fix #1566 alphabetic characters are not accepted as valid entries

- src/aria/popups/Beans.js
- src/aria/popups/PopupManager.js
- src/aria/touch/widgets/Popup.js
- src/aria/touch/widgets/PopupCfgBeans.js
- src/aria/widgets/container/Dialog.js
- test/aria/widgets/container/dialog/dynamicZIndex/BaseDynamicZIndexTestCase.js
- test/aria/widgets/container/dialog/dynamicZIndex/DynamicZIndexClickTestCase.js
- test/aria/widgets/container/dialog/dynamicZIndex/DynamicZIndexTestSuite.js
- test/aria/widgets/container/dialog/dynamicZIndex/innerPopup/DynamicZIndexInnerPopupTestCase.js
- test/aria/widgets/container/dialog/dynamicZIndex/innerPopup/DynamicZIndexInnerPopupTestTpl.tpl
This commit fixes regressions introduced by commit 8fed6379173c4bfbc48b2d2d962bd197d8edde9a (#1555): if a dialog contains widgets which have a popup (such as the dropdown list of an `@aria:Select`, or the validation error popup of most widgets) the popup is often displayed behind the dialog.
This is fixed by adding a new `zIndexKeepOpenOrder` property on popups, which, when set to `true` (which is the default), makes sure the newly opened popup is always kept in front of any popup that was opened before.
This property is set to `false` on all dialogs, to make sure they can be reordered as needed.
> Fix regressions caused by the dynamic zIndex popup management feature

- test/aria/widgets/form/multiselect/downArrowKeyPreventDef/MSDownArrowKey.js
This PR makes the `test.aria.widgets.form.multiselect.downArrowKeyPreventDef.MSDownArrowKey`
test more reliable by using the common `waitForDropDownPopup` method instead of re-implementing it in an incomplete way.
> Making the MSDownArrowKey test use waitForDropDownPopup

- src/aria/jsunit/JawsTestCase.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/datePicker/DatePickerJawsTest1.js
- test/aria/widgets/wai/datePicker/DatePickerTestTpl.tpl
This commit adds the `aria.jsunit.JawsTestCase` base class to help writing tests to be run with the Jaws screen reader enabled.
It also adds the `test.JawsTestSuite` class which is intended to reference all test cases designed to be run with Jaws enabled.
It also includes a first Jaws test, which can also be used as an example to write further tests: `test.aria.widgets.wai.datePicker.DatePickerJawsTest1`
> Allowing to write Jaws automatic tests

- src/aria/widgets/form/TextInput.js
- test/aria/widgets/form/TextInputTest.js
- test/aria/widgets/form/TextareaTest.js
This PR fixes a regression introduced by commit f9d30b69f19e3d472f6b4c93ddbbb210776507d8.
On IE9 and IE10, setting the selection on the focus event handler itself does not work, it has to be delayed.
> Fixing test.aria.widgets.autoselect.programmatic.AutoSelect on IE9 and IE10

- src/aria/popups/PopupManager.js
- test/aria/popups/focus/FocusTest.js
- test/aria/widgets/container/dialog/DialogTestSuite.js
- test/aria/widgets/container/dialog/closePopupScroll/ClosePopupScrollTest.js
- test/aria/widgets/container/dialog/closePopupScroll/ClosePopupScrollTestTpl.tpl
- test/aria/widgets/container/dialog/escKey/multipleDialogs/EscapeOnModalAndNonModalTest.js
- test/aria/widgets/container/dialog/escKey/multipleDialogs/EscapeOnModalTest.js
This commit removes some code which was trying to focus the first element of a popup when another popup was closed. This behavior was disturbing as it could scroll to the top of the dialog in case the first element was not visible.
> No longer scrolls to the top of the dialog when closing a popup

- src/aria/widgets/container/Dialog.js
As the aria.utils.dragdrop.Drag and aria.utils.resize.Resize utilities are loaded asynchronously (only if the dialog configuration requires those classes), it is possible that the dialog is disposed before those
classes are loaded, so the callback should check it before doing anything else.
> Issue when a resizable/movable dialog is disposed shortly after its creation

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/controllers/AutoCompleteController.js
- src/aria/widgets/form/AutoComplete.js
- src/aria/widgets/form/list/CfgBeans.js
- src/aria/widgets/form/list/ListController.js
- src/aria/widgets/form/list/templates/LCTemplate.tpl
- src/aria/widgets/form/list/templates/ListTemplate.tpl
- test/JawsTestSuite.js
- test/aria/widgets/wai/autoComplete/AutoCompleteBaseTest.js
- test/aria/widgets/wai/autoComplete/AutoCompleteJawsTest1.js
- test/aria/widgets/wai/autoComplete/AutoCompleteJawsTest2.js
- test/aria/widgets/wai/autoComplete/AutoCompleteTpl.tpl
- test/aria/widgets/wai/autoComplete/AutoCompleteTplScript.js
The compatibility of the aria:AutoComplete widget with JAWS on IE 11 is improved: it is now possible to specify a message to be read when the number of displayed suggestions changes and to change the message which is read for each suggestion.
> WAI-ARIA Improvements  for the AutoComplete

- src/aria/DomEvent.js
- src/aria/widgets/form/AutoComplete.js
- src/aria/widgets/form/DatePicker.js
- src/aria/widgets/form/DropDownTextInput.js
- src/aria/widgets/form/DropDownTrait.js
- src/aria/widgets/form/MultiSelect.js
- src/aria/widgets/form/list/List.js
- test/aria/widgets/wai/WaiTestSuite.js
- test/aria/widgets/wai/dropdown/AutoCompleteDropdownTogglingTest.js
- test/aria/widgets/wai/dropdown/Base.js
- test/aria/widgets/wai/dropdown/DatePickerDropdownTogglingTest.js
- test/aria/widgets/wai/dropdown/DropdownTestSuite.js
- test/aria/widgets/wai/dropdown/MultiAutoCompleteDropdownTogglingTest.js
- test/aria/widgets/wai/dropdown/MultiSelectDropdownTogglingTest.js
- test/aria/widgets/wai/dropdown/SelectBoxDropdownTogglingTest.js
- test/aria/widgets/wai/dropdown/SelectDropdownTogglingTest.js
- test/aria/widgets/wai/dropdown/Tpl.tpl
Now dropdowns can be opened and closed by using the keyboard accelerator <kbd>shift+F10</kbd>.
This disables the down arrow key for opening the dropdowns when `waiAria` is activated.
Also, `AutoComplete` based widgets won't have their dropdown opened if they don't have the expand button enabled (however the keys combination will work for closing the dropdown).
This required a little fix: now the full event object is passed to some event handlers functions. This enables giving more information about the event, which is sometimes needed. The API has been kept backward compatible.
> feat - WAI-ARIA - Dropdowns visibility toggling

- src/aria/jsunit/RobotPhantomJS.js
The backspace key was not correctly sent to PhantomJS by `RobotPhantomJS` and this apparently triggered a navigation in the iframe to some previous test, resulting in a timeout.
Especially, for the Aria Templates test campaign, this commit fixes the random issue with `AdaptToContentWidthTest`, when it is run in the same
PhantomJS instance as `ExternalHashNavigationTest`.
> Fix a random error in robot tests which use the backspace key in PhantomJS

- src/aria/widgets/container/Dialog.js
This PR fixes an issue with commit ba8b45d (#1591): as `document.activeElement` can be null on some browsers, it is better to check whether it is non-null before using it.
> document.activeElement can be null on some browsers

- test/EnhancedRobotTestCase.js
- test/aria/templates/keyboardNavigation/actionWidgets/ActionWidgetsTestTpl.tpl
- test/aria/templates/keyboardNavigation/dialog/escape/Base.js
- test/aria/templates/keyboardNavigation/dialog/escape/Tpl.tpl
- test/aria/widgets/form/multiselect/escapeKey/MultiSelectTpl.tpl
- test/aria/widgets/wai/dropdown/Tpl.tpl
- test/aria/widgets/wai/icon/IconTestTpl.tpl
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogTest.js
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogTestTpl.tpl
- now links are focused by clicking on them instead of using the programmatic way `.focus`
- all links used to get focus have now a `tabindex` property and no `href`, in order to avoid unwanted navigation or else
- made the "Dialog escape test" more robust
- fixed the "Modal Dialog" test on IE 8 by using the proper element's property
> fix #1596 fixed the "Modal Dialog" test on IE 8 and made a few more robust

- test/aria/widgets/form/multiselect/MultiSelectRobotTestCase.js
- test/aria/widgets/form/multiselect/downArrowKey/MultiSelect.js
- test/aria/widgets/form/multiselect/longlist/test1/MsLongList.js
- test/aria/widgets/form/multiselect/longlist/test2/MsLongList.js
- test/aria/widgets/wai/autoComplete/AutoCompleteBaseTest.js
`aria.utils.SynEvents` does not seem to correctly simulate key events on Edge, so this commit changes the following tests to use the robot, which fixes them:
- `test.aria.widgets.form.multiselect.longlist.test1.MsLongList`
- `test.aria.widgets.form.multiselect.longlist.test2.MsLongList`
- `test.aria.widgets.form.multiselect.downArrowKey.MultiSelect`
- `test.aria.widgets.wai.autoComplete.AutoCompleteWaiTestCase`
- `test.aria.widgets.wai.autoComplete.AutoCompleteGlobalNonWaiTestCase`
- `test.aria.widgets.wai.autoComplete.AutoCompleteGlobalWaiTestCase`
- `test.aria.widgets.wai.autoComplete.AutoCompleteNonWaiTestCase`
> Using the robot instead of Syn to fix several tests on Edge

- test/aria/core/environment/Customizations.js
This PR fixes random failures of `test.aria.core.environment.Customizations`, by waiting for the load of the first customization descriptor to be finished before loading another one.
To be sure that this PR fixes the issue, I have run several times in a loop a short campaign containing `test.aria.core.environment.Customizations` on travis-ci until the campaign fails.
- Without this fix, there is a failing campaign in less than 5 min, after 41 iterations in [this travis build](https://travis-ci.org/divdavem/ariatemplates/builds/109917850)
- With this fix, there is no failing campaign after more than 30 min and 600 iterations in [this travis build](https://travis-ci.org/divdavem/ariatemplates/builds/109920542)
> Random failures of test.aria.core.environment.Customizations

- src/aria/widgets/container/Dialog.js
- test/EnhancedRobotTestCase.js
- test/aria/widgets/wai/popup/dialog/modal/Base.js
- test/aria/widgets/wai/popup/dialog/modal/FirstTest.js
- test/aria/widgets/wai/popup/dialog/modal/FourthTest.js
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogJawsTest.js
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogTestSuite.js
- test/aria/widgets/wai/popup/dialog/modal/Model.js
- test/aria/widgets/wai/popup/dialog/modal/SecondTest.js
- test/aria/widgets/wai/popup/dialog/modal/ThirdTest.js
- test/aria/widgets/wai/popup/dialog/modal/Tpl.tpl
- test/aria/widgets/wai/popup/dialog/modal/TplScript.js
- the biggest change is that I have split the wai Modal Dialog test to allow parallelization and avoid timeouts too (I therefore removed the timeout increase for PhantomJS)
- made some tests even more robust by adding a delay before clicks to avoid unwanted double-clicks
- fixed the Dialog implementation in IE7 (hiding elements): Element.hasAttribute doesn't exist
- fixed the wai Modal Dialog test in Firefox 3: Element.parentElement doesn't exist
closes #1601
> fix #1601 fixed the wai Modal dialog (test & implementation) and made a few more robust

- src/aria/widgets/container/Dialog.js
- test/aria/widgets/container/dialog/autoFocus/AutoFocusTest.js
This commit fixes `test.aria.widgets.container.dialog.autoFocus.AutoFocusTest` on IE 8 and IE 10.
> fix AutoFocusTest on IE 8 and IE 10

- test/aria/widgets/container/dialog/closePopupScroll/ClosePopupScrollTestTpl.tpl
This PR fixes `test.aria.widgets.container.dialog.closePopupScroll.ClosePopupScrollTest`
on IE9. It seems that auto-focusing the first element in the dialog prevents the following `scrollIntoView` on IE 9 (only).
> fix/test ClosePopupScrollTest on IE 9

- test/aria/utils/dragdrop/fixedElements/FixedElementTestTemplate.tpl
This PR fixes `test.aria.utils.dragdrop.fixedElements.FixedElementTest` on IE 8, when run with [vbox-robot](https://github.com/attester/vbox-robot).
On IE 8, the following strange behavior happens: when the user starts to drag and drop a selected area (with a physical mouse, such as the one simulated by [vbox-robot](https://github.com/attester/vbox-robot), not the [robot-server](https://github.com/attester/robot-server)), the execution of script tags is temporarily delayed until the mouse is released.
As we wait for the execution of the JSON-P request from [vbox-robot](https://github.com/attester/vbox-robot) before sending the command to release the mouse, the test never ends successfully.
In this test, it is a mistake to have something selected, so, adding the unselectable attribute …
> fix test.aria.utils.dragdrop.fixedElements.FixedElementTest on IE 8

- src/aria/widgets/form/AutoComplete.js
- test/aria/widgets/wai/autoComplete/AutoCompleteJawsTest1.js
This PR fixes the following issue with the aria:AutoComplete widget in Jaws 16: when the suggestions list appears, the status was most of the time not read to notify the user that some suggestions are available.
> fix WAI-ARIA issue with the aria:AutoComplete widget in Jaws 16

- package.json
- scripts/attest.js
This PR allows to use the `attesterLauncherConfig` npm configuration parameter to specify an attester-launcher configuration file to be used with the `npm run attest` command, when the `--browsers=...` switch is used.
Here is a sample command showing how to configure the `attesterLauncherConfig` parameter:
```
npm config set ariatemplates:attesterLauncherConfig 'c:\\attesterLauncherConfig.yml'
```
Then, if that configuration file contains entries for the `Chrome` and `Firefox` browsers, it is possible to run `test.aria.AriaTest` on those 2 browsers with:
```
npm run attest -- --browsers=Chrome,Firefox test.aria.AriaTest
```
> Allowing to use attesterLauncher with "npm run attest"

- test/aria/widgets/wai/datePicker/DatePickerJawsTest1.js
It seems that Jaws 16 no longer say "entering application region" nor "leaving application region" in this test.
> Fixing DatePickerJawsTest1 with Jaws 16

- src/aria/jsunit/JawsTestCase.js
- test/EnhancedJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogJawsTest.js
- test/aria/widgets/wai/tabs/TabsJawsTest.js
- the `TabJawsTest` now ignores irrelevant content, especially the links that are clicked to have focus.
- the `EnhancedJawsTestCase` now supports the use of a filter
- the `JawsTestCase` now logs more information when there is an assert error
> fix Fixed the TabsJawsTest (by filtering) and improved the JAWS test utilities

- src/aria/utils/String.js
String.trim is a non-standard method implemented in Firefox:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_generic_methods
This PR removes the dependency on this method.
This also fixes the new `test.aria.utils.String.testNullTrim` test method which was introduced in #1626 (in commit afa3a47647ccd2a2c6f7285d1b039150e8049cfe) and was failing on Firefox.
> Removing dependency on non-standard String.trim function

- src/aria/widgets/container/Fieldset.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/fieldset/FieldsetLabelJawsTestCase.js
- test/aria/widgets/wai/fieldset/FieldsetLabelJawsTestCaseTpl.tpl
This change marks the current label with "aria-hidden", and adds another span containing the class "xSROnly" with the label content, and renders this span in the correct position before the frame.
_Note: this change is only switched on when accessibility is enabled._
> feat WAI-ARIA fixes an issue with the Fieldset widget label being read at the end of the Fieldset

- src/aria/touch/Event.js
- src/aria/utils/$SafeTap.js
- src/aria/widgets/form/DatePicker.js
- src/aria/widgets/frames/FrameWithIcons.js
In order to fix issues when trying to open the DatePicker popup (or popups of similar widgets), we now listen to the tap event instead of the click event on touch devices.
Touch devices are detected using `aria.utils.Device.isTouch()`.
`aria.touch.Tap` is only loaded if a touch device is detected.
> Listening to tap events for popup icons of DatePicker and similar widgets

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Dialog.js
- src/aria/widgets/container/DialogStyle.tpl.css
- test/JawsTestSuite.js
- test/aria/widgets/container/dialog/resize/AbstractResizableDialogTestCase.js
- test/aria/widgets/container/dialog/resize/test5/OverlayOnResizeScrollTestCase.js
- test/aria/widgets/container/dialog/sizes/DialogMaxWidthTestCase.js
- test/aria/widgets/wai/popup/dialog/focusableItems/FocusableCloseButtonJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/focusableItems/FocusableItemsJawsTestSuite.js
- test/aria/widgets/wai/popup/dialog/focusableItems/FocusableTitleJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/focusableItems/Tpl.tpl
- test/aria/widgets/wai/popup/dialog/focusableItems/TplScript.js
- test/aria/widgets/wai/popup/dialog/focusableItems/UnfocusableCloseButtonJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/focusableItems/UnfocusableTitleJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/modal/Base.js
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogJawsTest.js
This PR adds 3 new configuration options for `aria:Dialog` widgets:
- `focusableTitle`: whether the title of the dialog is focusable. By default, it is set to true if `waiAria` is true.
- `focusableClose` and `focusableMaximize`: whether the corresponding button is focusable. By default, it is set to true if `waiAria` is true and the corresponding label is defined.
> Making dialog title and buttons focusable or not by configuration

- test/aria/widgets/form/autocomplete/expandbutton/test4/ExpandButtonCheck.js
This PR makes `ExpandButtonCheck` more stable by using `waitFor` functions.
(cf a random failure here: https://travis-ci.org/ariatemplates/ariatemplates/builds/142181917#L1287)
> Fixing random failures of ExpandButtonCheck

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/errorlist/CfgBeans.js
- src/aria/widgets/errorlist/ErrorList.js
- src/aria/widgets/errorlist/ErrorListController.js
- src/aria/widgets/errorlist/ErrorListTemplate.tpl
- test/JawsTestSuite.js
- test/aria/widgets/wai/errorlist/titleTag/ErrorListTitleTagJawsTestCase.js
- test/aria/widgets/wai/errorlist/titleTag/ErrorListTitleTagTpl.tpl
This PR adds the `titleTag` property on the `ErrorList` widget to allow setting the tag used for the title in the `ErrorList` widget.
This is especially useful for accessibility: screen readers often provide a way to navigate through the heading tags of the page.
> Adding the titleTag property on the ErrorList widget

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Dialog.js
- src/aria/widgets/container/DialogStyle.tpl.css
- test/JawsTestSuite.js
- test/aria/widgets/wai/popup/dialog/modal/ModalDialogJawsTest.js
- test/aria/widgets/wai/popup/dialog/titleTag/DialogTitleTagJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/titleTag/DialogTitleTagTpl.tpl
This PR adds the `titleTag` property to the Dialog widget to allow setting the tag used for the title in the dialog.
By default, the tag used for dialogs is now `h1` when `waiAria` is `true` and `span` (as before) otherwise.
This is especially useful for accessibility: screen readers often provide a way to navigate through the heading tags of the page.
> Adding the titleTag property on the Dialog widget

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Dialog.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/popup/dialog/waiEscapeMsg/DialogEscapeJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/waiEscapeMsg/DialogEscapeTpl.tpl
This PR adds the following properties on the dialog widget:
- `waiEscapeMsg`: If this property is defined and if `waiAria` is activated, the user has to press escape twice (instead of only once) to close the dialog. This property specifies the message to read after the user pressed escape the first time.
- `waiCloseMsg`: When `waiAria` is activated, this property specifies the message to read when the modal dialog is closed.
> Adding the waiEscapeMsg and waiCloseMsg properties on the Dialog widget

- src/aria/widgets/form/RadioButton.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/input/WaiInputTestSuite.js
- test/aria/widgets/wai/input/radiobutton/initiallyDisabled/InitiallyDisabledRadioButtonsJawsTestCase.js
- test/aria/widgets/wai/input/radiobutton/initiallyDisabled/InitiallyDisabledRadioButtonsTestCase.js
- test/aria/widgets/wai/input/radiobutton/initiallyDisabled/InitiallyDisabledRadioButtonsTpl.tpl
- test/aria/widgets/wai/input/radiobutton/initiallyDisabled/InitiallyDisabledRadioButtonsTplScript.js
Initially disabled radio buttons were excluded from the array of all radio button instances and never added (even when re-enabled), which prevented them from reacting correctly to arrow up and down navigation.
This commit makes sure all radio buttons (whether they are enabled or not) are present in the array of all radio button instances. Disabled radio buttons are simply skipped when looping through the array.
> Initially disabled radio buttons misbehaving when enabled

- src/aria/widgets/form/CheckBox.js
- src/aria/widgets/form/RadioButton.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/input/checkbox/CheckBoxDisabledBaseJawsTestCase.js
- test/aria/widgets/wai/input/checkbox/CheckboxDisabledTestCaseTpl.tpl
- test/aria/widgets/wai/input/checkbox/CheckboxDynamicallyDisabledJawsTestCase.js
- test/aria/widgets/wai/input/checkbox/CheckboxInitiallyDisabledJawsTestCase.js
- test/aria/widgets/wai/input/checkbox/CheckboxNotCheckedDisabledJawsTestCase.js
This PR fixes the following issue in IE 11 / Jaws 16: in some cases a disabled checked checkbox is read as "not checked unavailable" instead of "checked unavailable".
> Jaws reads "not checked unavailable" when the checkbox is checked (and disabled)

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Tab.js
- src/aria/widgets/container/TabPanel.js
- test/aria/widgets/wai/tabs/Base.js
- test/aria/widgets/wai/tabs/update1/TabsJawsTest.js
- test/aria/widgets/wai/tabs/update1/Tpl.tpl
- test/aria/widgets/wai/tabs/update1/TplCSS.tpl.css
Tab:
- tabs are now "a" elements, and all the accessibility attributes, as well as the tabindex for focusing, are put on this element
- ability to add a wrapper element around the "a", with a custom tag
- support for: aria-hidden, aria-label, aria-labelledby, aria-describedby
TabPanel:
- now the tabIndex defaults to -1
Global behavior:
- when a Tab is selected, the first element of its associated TabPanel is focused
Glitches:
- when clicking on a Tab to select it, since the focus is set to the TabPanel the Tab title is not read
> feat #1665 WAI-ARIA - Tab & TabPanel - Specifications update

- src/aria/utils/String.js
- src/aria/widgets/CfgBeans.js
- src/aria/widgets/action/ActionWidget.js
- src/aria/widgets/action/Button.js
- src/aria/widgets/action/Link.js
- src/aria/widgets/action/SortIndicator.js
- src/aria/widgets/container/Tab.js
- src/aria/widgets/container/TabPanel.js
- test/EnhancedJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/Base.js
- test/aria/widgets/wai/input/actionWidget/Button.js
- test/aria/widgets/wai/input/actionWidget/CSS.tpl.css
- test/aria/widgets/wai/input/actionWidget/IconButton.js
- test/aria/widgets/wai/input/actionWidget/Link.js
- test/aria/widgets/wai/input/actionWidget/SimpleButton.js
- test/aria/widgets/wai/input/actionWidget/SortIndicator.js
- test/aria/widgets/wai/input/actionWidget/Suite.js
- test/aria/widgets/wai/input/actionWidget/Tpl.tpl
- test/aria/widgets/wai/input/actionWidget/TplScript.js
- test/aria/widgets/wai/tabs/Base.js
- test/aria/widgets/wai/tabs/update1/TabsJawsTest.js
- test/aria/widgets/wai/tabs/update1/Tpl.tpl
- test/aria/widgets/wai/tabs/update1/TplCSS.tpl.css
The impacted widgets are the following:
- ActionWidget
- Button, including the simple button where the element is now a "button" instead of an "input"
- IconButton
- Link
- SortIndicator
Implemented attributes are (on the left the WAI-ARIA attribute name, on the right the widget's property changing its value):
- aria-label: waiLabel
- aria-labelledby: waiLabelledBy
- aria-describedby: waiDescribedBy
- aria-disabled: disabled
> feat #1666 WAI-ARIA - ActionWidget - Implementation of labels, description and disabled

- package.json
- src/aria/jsunit/JawsTestCase.js
This PR adds some line breaks in the error message of Jaws test cases so that it is easier to compare the actual Jaws history with the expected one.
> Improving the readability of Jaws test case failures

- scripts/attest.js
This PR allows to use CTRL-C when running the "npm run attest" command, in order to interrupt it properly (including on Windows).
Cf the similar commit in attester: https://github.com/attester/attester/commit/478634091e9e8abe80dad9aae12a230ac432b5d1
> Adding support for SIGINT for "npm run attest"

- src/aria/jsunit/JawsTestCase.js
- test/aria/widgets/wai/errorlist/binding/ErrorListBindingJawsTestCase.js
- test/aria/widgets/wai/errorlist/titleTag/ErrorListTitleTagJawsTestCase.js
- test/aria/widgets/wai/iconLabel/IconLabelJawsTest.js
- test/aria/widgets/wai/input/checkbox/CheckBoxDisabledBaseJawsTestCase.js
- test/aria/widgets/wai/input/checkbox/CheckboxJawsTestCase.js
- test/aria/widgets/wai/input/radiobutton/RadioButtonGroupJawsTestCase.js
- test/aria/widgets/wai/input/radiobutton/initiallyDisabled/InitiallyDisabledRadioButtonsJawsTestCase.js
- test/aria/widgets/wai/multiselect/MultiSelectJawsTest.js
- test/aria/widgets/wai/multiselect/MultiSelectTabJawsTest.js
- test/aria/widgets/wai/popup/dialog/titleTag/DialogTitleTagJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/waiEscapeMsg/DialogEscapeJawsTestCase.js
This PR refactors the way filters for Jaws history are applied in Jaws test cases:
* `retrieveJawsHistory` no longer does any filtering, it returns the raw Jaws history
* `assertJawsHistoryEquals` now first executes `filterJawsHistory` before any provided filter function
* `filterJawsHistory` executes by default the 3 following common filters on all tests:
* `normalizeSpaces` (can be disabled with `this.skipNormalizeSpaces = true`)
* `removeNoise` (can be disabled with `this.skipRemoveNoise = true`)
* `removeDuplicates` (can be disabled with `this.skipRemoveDuplicates = true`)
* `removeNoise` can be configured by changing the array of regular expressions stored in `this.noiseRegExps`
> Factorizing filters for Jaws test cases, improves the stability of those tests

- src/aria/widgets/TemplateBasedWidget.js
- src/aria/widgets/form/AutoComplete.js
- src/aria/widgets/form/list/List.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/autoComplete/preselect/AutoCompletePreselectJawsTest1.js
- test/aria/widgets/wai/autoComplete/preselect/AutoCompletePreselectJawsTest2.js
- test/aria/widgets/wai/autoComplete/preselect/AutoCompleteTpl.tpl
- test/aria/widgets/wai/autoComplete/preselect/AutoCompleteTplScript.js
When using the `@aria:AutoComplete` component with `waiAria = true`, the `aria-activedescendant` attribute was not set until the user navigates the suggestions with up/down arrow keys.
This was an issue when a suggestion is preselected while the user types (which can happen, for example, if the `preselect` property is set to `"always"`)
> fix aria-activedescendant initially not set for the autocompletete widget

- src/aria/widgets/Widget.js
- src/aria/widgets/environment/WidgetSettings.js
- src/aria/widgets/environment/WidgetSettingsCfgBeans.js
- test/aria/widgets/WidgetsTestSuite.js
- test/aria/widgets/defaults/CheckDefaultsTest.js
- test/aria/widgets/defaults/CheckDefaultsTestTpl.tpl
This PR adds the `widgetDefaults` parameter in the environment, allowing to specify a default value for any property of any widget in the Aria widget library.
For example, to set the `calendarNumberOfUnits` property for all instances of the `@aria:DatePicker` widget (if those instances do not specify any value for this property):
```js
aria.core.AppEnvironment.setEnvironment({
widgetDefaults: {
DatePicker: {
calendarNumberOfUnits: 5
}
}
});
```
> Configurable default values for any widget property of the Aria library

- src/aria/jsunit/TestRunner.js
Now line returns are properly displayed, and the errors descriptions are escaped for safety.
> feat/test #1671 Improved the test output for the default JSUnit TestRunner.

- src/aria/widgets/action/Button.js
No matter the button is a simpleHtml one or not. we always set the button as disabled via the proper attribute when needed.
We previously were setting it only in case of a simpleHTML button.
I am doing it all the time, there is no need is to check that `waiAria` is active.
> Disabled button to actually be disabled [JAWS]

- src/aria/widgets/action/ActionWidget.js
- src/aria/widgets/action/Link.js
- test/aria/widgets/wai/input/actionWidget/Base.js
Also made the following change to all "ActionWidget" based widgets: now the "aria-disabled" attribute is not set anymore in WAI-ARIA mode, "disabled" must be sufficient.
For now, this PR depends on https://github.com/ariatemplates/ariatemplates/pull/1662 Without that, the following tests are failing (even though the final expected output has already been fixed):
- test.aria.widgets.wai.input.actionWidget.Button
- test.aria.widgets.wai.input.actionWidget.IconButton
References:
- AT-1398
- PTR 11630074
> feat #1675 Implement the "disabled" attribute for the Link widget

- test/aria/widgets/form/select/SelectTestSuite.js
test.aria.widgets.form.select.valueAndOptionsBinding.SelectTemplateTestCase is missing
> fix SelectTemplateTestCase missing in test suite

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/form/MultiSelect.js
- src/aria/widgets/form/TextInput.js
- test/JawsTestSuite.js
- test/aria/widgets/wai/multiselect/readOnlyTextField/ReadOnlyTextFieldJawsTestCase.js
- test/aria/widgets/wai/multiselect/readOnlyTextField/ReadOnlyTextFieldTpl.tpl
This commit adds the `readOnlyTextField` property to the multiselect. If true, the user can only modify the value of the widget by opening the popup (the text field is not modifiable).
> New readOnlyTextField property on the aria:MultiSelect widget

- src/aria/widgets/form/Input.js
If there is no `waiLabel` or `waiLabelledBy` property and the widget (which extends `aria.widgets.form.Input`) has a label, the id of that label is used for the `waiLabelledBy` property.
> Adding a default value for aria-labelledby for input widgets.

- test/aria/widgets/wai/input/checkbox/CheckboxJawsTestCase.js
`test.aria.widgets.wai.input.checkbox.CheckboxJawsTestCase` sometimes failed because Jaws sometimes breaks `Checkbox B check box not checked` into two lines in Jaws history (the new line being inserted before `check box`).
> Improving stability of CheckboxJawsTestCase

- test/aria/widgets/wai/fieldset/FieldsetLabelJawsTestCase.js
- test/aria/widgets/wai/input/radiobutton/RadioButtonGroupJawsTestCase.js
After commit 24960cb98cef30f45e0cd897c64e0c317eecddff, the following tests failed because the corresponding radio buttons now have a label (which was not expected in Jaws history):
- `test.aria.widgets.wai.fieldset.FieldsetLabelJawsTestCase`
- `test.aria.widgets.wai.input.radiobutton.RadioButtonGroupJawsTestCase`
This PR updates the expected history in those tests.
> Updating Jaws tests after adding a default value for aria-labelledby

- test/aria/core/io/IOXDRTestCase.js
We now use `echo.ariatemplates.com`, as `pipes.yahooapis.com` is no longer available.
> IOXDRTestCase no longer uses pipes.yahooapis.com to test XDR

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/action/ActionWidget.js
- test/aria/widgets/wai/input/actionWidget/hasPopup/ButtonJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/hasPopup/ButtonJawsTestCaseTpl.tpl
- test/aria/widgets/wai/input/actionWidget/hasPopup/LinkJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/hasPopup/LinkJawsTestCaseTpl.tpl
This PR adds the `waiHasPopup` property on all widgets which extend `ActionWidget` (`@aria:Button`, `@aria:Link`, ...).
> Adding waiHasPopup on widgets extending ActionWidget

- src/aria/utils/Date.js
- src/aria/utils/Type.js
- test/aria/utils/DateTestCase.js
- test/aria/utils/TypeTestCase.js
Before this commit:
```js
aria.utils.Date.interpret("-365"); // returns today - 365 days
aria.utils.Date.interpret("+365"); // returns today + 365 days
aria.utils.Date.interpret("-366"); // returns null
aria.utils.Date.interpret("+366"); // returns null
aria.utils.Date.interpret("1SEP2016/-365"); // returns Wed Sep 02 2015
aria.utils.Date.interpret("1SEP2016/+365"); // returns Fri Sep 01 2017
aria.utils.Date.interpret("1SEP2016/-366"); // returns null
aria.utils.Date.interpret("1SEP2016/+366"); // returns null
```
After this commit:
```js
aria.utils.Date.interpret("-365"); // still returns today - 365 days
aria.utils.Date.interpret("+365"); // still returns today + 365 days
aria.utils.Date.interpret("-366"); // now returns today - 366 days
aria.utils.Date.interpret("+366"); // now returns …
```
> Removing arbitrary limit of +/-365 in the date parser

- src/aria/utils/Array.js
- test/aria/utils/ArrayTestCase.js
This pull request would like to add the Array.prototype.every method to the aria.utils.Array object. This is to polyfill older versions of the browser and also to have a clean way of performing tasks on Arrays. The purpose of this addition is to allow us to write recursion that will replicate the break functionality, so we don't have to waste time looping through the list when the required item is found.
> Add Array.prototype.every to aria.utils.Array. New test added to ArrayTestCase

- src/aria/core/Browser.js
- test/aria/core/useragent/BrowserAndDeviceTestCase.js
- test/aria/core/useragent/UseCases.js
The following properties of aria.core.Browser were true only on the desktop version of the corresponding browsers:
- isSafari
- isIE
- isOpera
They are now true both on the desktop and mobile versions.
> isSafari, isIE and isOpera were not true on the mobile versions

- src/aria/utils/Json.js
- test/aria/utils/JsonTestCase.js
This commit adds some checks to remove `aria:parent` properties on an object when that object no longer has any recursive listener and no longer has any parent in `aria:parent`. This fixes some memory leaks which can occur in case some parts of the data model are reused inside new containers and old containers are no longer used but still pointing to the reused parts of the data model (so the `aria:parent` properties on the reused parts of the data model still pointed to the old objects, even though there was no recursive listener any more in that old part of the data model).
> Removing `aria:parent` properties when they are no longer useful

- src/aria/widgets/Text.js
- src/aria/widgets/Widget.js
- src/aria/widgets/action/Button.js
- src/aria/widgets/action/SortIndicator.js
- src/aria/widgets/container/Tab.js
- test/aria/widgets/action/button/clickNotWorking/ButtonClickNotWorkingRobotTestCase.js
- test/aria/widgets/action/button/clickNotWorking/ButtonClickNotWorkingRobotTestCaseTpl.tpl
- test/aria/widgets/action/button/clickNotWorking/ButtonClickNotWorkingRobotTestCaseTplScript.js
This commit adds support for mouseenter/mouseleave events in aria widgets (by simulating those events in all browsers from the mouseover/mouseout events).
This fixes an issue which prevented the button from working on some browsers (including Chrome) when clicking right at the top of the &lt;span&gt; element (inside the larger &lt;button&gt; element) because that element moves down when clicking, leading to a mouseout event on the span but there is no mouseleave event on the larger &lt;button&gt; element.
> Using mouseenter/mouseleave instead of mouseover/mouseout in widgets

- test/aria/templates/customization/CustomTemplateTestCase.js
This commit fixes a random issue happening at the end of `CustomTemplateTestCase`:
restoring the environment at the end of the test triggers an XHR which can cause issues on the following tests in the test campaign.
> fix/test test.aria.templates.customization.CustomTemplateTestCase

- package.json
It is no longer useful to rely on our fork of ua-parser-js, now that our changes have been integrated:
- https://github.com/faisalman/ua-parser-js/pull/122
- https://github.com/faisalman/ua-parser-js/pull/139
> Updating ua-parser-js

- test/ciLauncher.yml
This increases the stability of the travis build.
> Reducing the number of phantomjs instances on travis

- src/aria/core/Log.js
When aria.core.Log is disposed, the previous code was replacing the error logging function by a function which displayed the error using alert. The alert could sometimes be triggered during the tests in IE 7 and
blocked the following tests. This commit replaces it with logs on the console.
> Removing alert when logging after aria.core.Log is disposed

- test/testConfigBuilder.js
`test.aria.widgets.container.dialog.viewportResize.ViewportHugeShrinkTestCase` was present in the repository without being part of a test suite, and has not been run during the release test campaign for a long time. It fails in all browsers except PhantomJS, but PhantomJS is known not to properly handle the size of the viewport (and this test is related to it).
More investigation should be done on this test to either fix it or remove it.
> Disabling ViewportHugeShrinkTestCase

- src/aria/utils/Delegate.js
- test/aria/core/CSSPrefixTestCase.js
This PR fixes `CSSPrefixTestCase` on Firefox 49 by changing the order in which prefixes are tested. `Moz` is now tested before `Webkit`, so that, on Firefox, `Moz` is chosen rather than `Webkit` (now that both seem to be supported on Firefox 49).
> fix/test #1707 test.aria.core.CSSPrefixTestCase

- test/testConfigBuilder.js
Using Firefox instead of PhantomJS to run TooltipRobotTestCase on travis-ci as TooltipRobotTestCase often fails on PhantomJS (for an unknown reason).
> Using Firefox instead of PhantomJS to run TooltipRobotTestCase on travis-ci

- test/aria/html/textarea/bind/BindableRobotTestCase.js
- test/aria/html/textinput/bind/BindableRobotTestCase.js
Depending on how fast the robot implementation is, `test.aria.html.textarea.bind.BindableRobotTestCase` and `test.aria.html.textinput.bind.BindableRobotTestCase` could fail in case the keys are typed quicker than the delay we use to simulate the type event.
This PR adds some pause between each character so that the corresponding type events do not combine several letters together.
Especially, this commit fixes both tests with the robot-server on Safari.
> Slowing down BindableRobotTestCase to make it more reliable

- test/aria/html/select/onchange/DataModelOnChangeRobotTestCase.js
This PR improves the reliability of `DataModelOnChangeRobotTestCase` by waiting for the focus and adding a pause after typing. This fixes the test on Safari with robot-server.
> Improving reliability of DataModelOnChangeRobotTestCase

- src/aria/utils/DomNavigationManager.js
- src/aria/widgets/container/Dialog.js
- test/aria/utils/domNavigationManager/CSS.tpl.css
- test/aria/utils/domNavigationManager/DomNavigationManagerJawsTestCase.js
- test/aria/utils/domNavigationManager/DomNavigationManagerRobotTestCase.js
- test/aria/utils/domNavigationManager/Tpl.tpl
- test/aria/utils/domNavigationManager/TplScript.js
The dialog did not use properly the new utility to hide other elements: it was using wrong reference elements.
Also improved the aria.utils.DomNavigationManager by not touching elements whose hidden state is managed by other entities (i.e. which have a aria-hidden without a registered request counter).
> fix #1710 Fixed test.aria.widgets.wai.popup.dialog.titleTag.DialogTitleTagJawsTestCase

- test/EnhancedRobotBase.js
- test/aria/utils/domNavigationManager/DomNavigationManagerRobotTestCase.js
- test/testConfigBuilder.js
Was using the method "focus" instead of triggering a user click.
Also improved a bit the test.EnhancedRobotBase class to accept both id or element as input for some functions.
> fix #1715 Fixed test.aria.utils.domNavigationManager.DomNavigationManagerRobotTestCase for IE 7, 8, 9

- test/aria/widgets/action/link/disabled/LinkDisabledRobotTestCase.js
- test/aria/widgets/action/link/disabled/LinkDisabledRobotTestCaseTpl.tpl
- test/aria/widgets/action/link/disabled/LinkDisabledRobotTestCaseTplScript.js
Now that `@aria:Link` widgets really have the disabled attribute when they are disabled, it seems IE 8 raises an error when aria.utils.SynEvent tries to click on them. This commit fixes this issue by using the robot implementation of SynEvent (aria.jsunit.SynEvent) instead of aria.utils.SynEvent.
> Fixing LinkDisabledTestCase on IE 8 (by making it a robot test)

- src/aria/core/IO.js
- test/aria/core/io/IOTransportTestCase.js
- test/aria/core/io/IOXDRTestCase.js
Now that CORS is largely implemented in browsers, this commit changes the default implementation of cross-domain requests to use CORS instead of the Flash-based implementation.
The Flash-based implementation can still be re-enabled by calling the `aria.core.IO.updateTransports` method in the following way:
```js
aria.core.IO.updateTransports({
'crossDomain' : 'aria.core.transport.XDR'
});
```
Note that this change is NOT backward compatible. Applications relying on the Flash-based implementation of cross-domain requests should use the above lines of code or migrate to CORS.
> Using CORS instead of Flash by default for cross-domain requests

- src/aria/widgets/container/Dialog.js
- test/aria/widgets/container/dialog/hiddenViewportResize/HiddenDialogViewportResizeTestCase.js
- test/aria/widgets/container/dialog/hiddenViewportResize/HiddenDialogViewportResizeTestCaseTpl.tpl
- test/testConfigBuilder.js
If a dialog is manually hidden (by setting its `display` CSS property to `none` and by updating the corresponding `isOpen` boolean on the popup object), its size will no longer be updated on viewport resize.
This avoids setting the size of the popup to 0 (as offsetWidth and offsetHeight can return 0 for elements which are not visible on the screen).
> Skip updating manually hidden dialogs on viewport resize

- src/aria/widgets/container/Tab.js
- src/aria/widgets/container/TabStyle.tpl.css
- test/aria/widgets/wai/tabs/TabsJawsTestCase.js
- test/aria/widgets/wai/tabs/update1/TabsUpdate1JawsTestCase.js
Blind users do not like the "tab" role because, just as the "application" role, it prevents them from using their navigation shortcuts. This commit simply removes the role attribute for tabs, and also adds the href attribute on the anchors so that tabs are recognized as links.
> Removing the "tab" role

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/action/Button.js
- src/aria/widgets/action/Link.js
- test/aria/widgets/wai/input/actionWidget/ariaHidden/ActionWidgetHiddenJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/ariaHidden/Tpl.tpl
- test/aria/widgets/wai/input/actionWidget/ariaHidden/TplScript.js
Now it is possible to set `waiLabelHidden` for all `ActionWidget` based widgets, in order to put the attribute aria-hidden around their actual (visual) label element.
AT-1571
PTR 12373188
> feat #1721 WAI-ARIA - ActionWidget - Implement aria-hidden (waiLabelHidden)

- src/aria/widgets/form/DatePicker.js
- src/aria/widgets/form/DropDownTextInput.js
- src/aria/widgets/form/InputWithFrame.js
- src/aria/widgets/form/MultiSelect.js
- src/aria/widgets/frames/CfgBeans.js
- src/aria/widgets/frames/FrameWithIcons.js
- test/aria/widgets/wai/datePicker/DatePicker1JawsTestCase.js
- test/aria/widgets/wai/datePicker/readDate/DatePickerReadDateJawsTestCase.js
- test/aria/widgets/wai/dropdown/icon/DropDownIconJawsTestCase.js
- test/aria/widgets/wai/dropdown/icon/Tpl.tpl
- test/aria/widgets/wai/dropdown/icon/TplScript.js
- test/aria/widgets/wai/iconLabel/IconLabelJawsTestCase.js
- test/aria/widgets/wai/input/label/DatePickerJawsTestCase.js
- test/aria/widgets/wai/input/label/LabelJawsBase.js
- test/aria/widgets/wai/input/label/MultiSelectJawsTestCase.js
- test/aria/widgets/wai/input/label/SelectBoxJawsTestCase.js
- test/aria/widgets/wai/multiselect/MultiSelectJawsTestCase.js
- test/aria/widgets/wai/multiselect/MultiSelectTabJawsTestCase.js
- test/aria/widgets/wai/multiselect/readOnlyTextField/ReadOnlyTextFieldJawsTestCase.js
This commit removes the `role="button"` attribute and adds a `tabindex` on the dropdown icon of the widgets which extend `DropDownTextInput` (`DatePicker`, `MultiSelect`...), so that those icons are not included in the list of buttons displayed by screen readers and become focusable by tab.
> Removing role="button" and adding a tabindex on dropdown icons

- src/aria/widgets/form/DatePicker.js
- test/aria/widgets/wai/datePicker/readDate/DatePickerReadDateJawsTestCase.js
An internal variable was not properly used to implement the feature, the fix was trivial. Test has been enhanced to check this use case.
> fix #1726 - WAI-ARIA - DatePicker - Date was read even with keystrokes not changing text

- test/aria/utils/accessibility/AccessibilityJawsTestCase.js
In some testing environments, the screen reader has to read multiple things, so it's better to wait longer so that everything is read properly.
> fix/test #1729 Fixed test.aria.utils.accessibility.AccessibilityJawsTestCase

- src/aria/widgets/container/TabPanel.js
- src/aria/widgets/container/TabPanelStyle.tpl.css
- test/aria/widgets/wai/tabs/TabsJawsTestCase.js
This focusable element is only added when `waiAria` is true, and has the same `aria-labelledby` attribute as the root element of the tab panel, so that, when focusing the tab panel, the title of the currently selected tab is read by screen readers.
> Adding a focusable element at the top of the TabPanel widget

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/action/Button.js
- src/aria/widgets/action/ButtonStyle.tpl.css
- test/aria/widgets/wai/input/actionWidget/buttonFocusableWhenDisabled/FocusableDisabledButtonJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/buttonFocusableWhenDisabled/FocusableDisabledButtonJawsTestCaseTpl.tpl
- test/aria/widgets/wai/input/actionWidget/buttonFocusableWhenDisabled/FocusableDisabledButtonJawsTestCaseTplScript.js
Blind users often navigate in a page with tab, which means they cannot notice disabled widgets, which are not focusable.
When those widgets are essential to understand the page, this is a problem, especially for buttons. This commit allows important buttons to be focusable when they are disabled, by setting the `focusableWhenDisabled` parameter to `true`.
> Adding the focusableWhenDisabled parameter on aria:Button widgets

- test/testConfigBuilder.js
This avoids having to update the repository for each new version of those browsers.
> Removing specific versions of Chrome and Firefox in testConfigBuilder.js

- src/aria/widgets/form/DatePicker.js
- src/aria/widgets/form/TextInput.js
- test/aria/widgets/form/textinput/onclick/withEvent/OnClickWithEventTemplate.tpl
- test/aria/widgets/form/textinput/onclick/withEvent/OnClickWithEventTemplateScript.js
- test/aria/widgets/form/textinput/onclick/withEvent/OnClickWithEventTestCase.js
Before this commit, the `onclick` event handler of the TextInput-based widgets did not receive any event object. This commit makes sure a `DomEventWrapper` object is passed to the event handler, as it is done in other widgets.
Note that this PR implements a subset of #1638
> Injecting DomEventWrapper in TextInput:onclick

- src/aria/core/Interfaces.js
If an object for which an interface wrapper has been created is never disposed through its $dispose method, the garbage collector can never collect it because the corresponding interface keeps a reference to it.
For example, assuming the `x.Y` class impements the `x.IY` interface, the following code creates a leak:
```js
for (var i = 0; i < 100000; i++) {
var myObj = new x.Y();
myObj.$interface("x.IY");
// The leak would not appear if myObj was disposed like this:
// myObj.$dipsose();
}
```
This commit avoids creating a leak in such a case by using a `WeakMap` in the interface in order to keep a reference to the underlying object without preventing the garbage collector from collecting the underlying
object and interface wrapper if there is no other reference to them anywhere.
(in case …
> Changing implementation of interface wrappers to avoid leaks

- tasks/task-atbuild.js
- tasks/task-easypackage.js
This PR fixes issues with the `easypackage` and `atbuild` grunt tasks when using npm3 (with its flat structure).
> easypackage and atbuild issues with npm3

- src/aria/templates/DomElementWrapper.js
- src/aria/templates/SectionWrapper.js
- src/aria/templates/TemplateCtxt.js
- test/aria/dom/logscheck/LogsCheckTestCase.js
- test/aria/html/textinput/autoselectapi/AutoselectTestCaseTplScript.js
- test/aria/templates/autorefresh/MultipleTestCase.js
- test/aria/templates/dynamicSection/DynSectionTestCase.js
- test/aria/templates/dynamicSection/testTwo/DynSectionTestTwoScript.js
- test/aria/templates/macrolibs/MacrolibsTestCase.js
- test/aria/templates/memoization/MemoTestCase.js
- test/aria/templates/scrollControl/ScrollControlTestCase.js
- test/aria/templates/section/SectionTestCase.js
- test/aria/templates/section/processingIndicator/ProcessingIndicatorOnSectionTestCase.js
- test/aria/templates/section/sectionAttributes/SectionAttributesTestCase.js
- test/aria/templates/section/sectionAttributes/binding/SectionAttributesBindingBase.js
- test/aria/utils/overlay/loadingIndicator/automatic/AutomaticTestCase.js
- test/aria/utils/overlay/loadingIndicator/ieScrollIssue2/IEScrollIssue2Base.js
- test/aria/utils/overlay/loadingIndicator/manual/ManualTestCase.js
- test/performance/leakOnRefresh/TemplateRefreshTestCase.js
Each time a call to `$getElementById` or `$getChild` is done on a template, a new `DomElementWrapper` object is created and, until this commit, the wrapper was also added to an array in the template context, with the only purpose of calling `$dispose` on all wrapper elements when the template is fully refreshed or disposed. If this does not happen (e.g. if there are only partial refreshes), and many calls to the `$getElementById` and `$getChild` functions are done, this creates a leak. With this commit, wrappers are no longer stored on the template context, it is up to the application to dispose them (if needed).
> Memory leak when calling $getElementById or $getChild on a template

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Dialog.js
- test/aria/widgets/wai/popup/dialog/waiOpenMsg/DialogOpenMsgJawsTestCase.js
- test/aria/widgets/wai/popup/dialog/waiOpenMsg/Tpl.tpl
- test/aria/widgets/wai/popup/dialog/waiOpenMsg/TplScript.js
The new `waiOpenMsg` property allows to specify a message to be read by screen readers when the dialog is opened.
> Adding the waiOpenMsg property on the aria:Dialog widget

- src/aria/core/Interfaces.js
Commit ff7921e66b5a12e6de8e31ca55be79c0c93a4fb0 from #1736 introduced a regression in the `linkItfWrappers` function on modern browsers (which have an implementation of `WeakMap`).
As a consequence, test.aria.modules.moduleReload.ModuleReload1TestCase and test.aria.modules.moduleReload.ModuleReload2TestCase fail on those browsers.
This pull request fixes this regression.
> Regression in linkItfWrappers after refactoring interface wrappers

- test/aria/widgets/wai/processingIndicator/TplScript.js
Following commit 925c9078cfea9cdaccab764330e217f18696fad6, the call to `$dispose` on `DomElementWrapper` objects returned by `$getElementById` is no longer done automatically. This commit adds a missing call to `$dispose` on a `DomElementWrapper` instance in a Jaws test case.
> Missing call to $dispose on DomElementWrapper

- test/testConfigBuilder.js
The following 3 tests were successful in 1.7.21 and started to fail in 1.7.22:
- test.aria.html.textinput.placeholder.PlaceholderTestCase
- test.aria.widgets.dropdown.touchDevices.AutoCompleteNoExpButPopupDesktopRobotTestCase
- test.aria.widgets.dropdown.touchDevices.AutoCompleteNoExpButPopupTouchRobotTestCase
This PR excludes them from the test campaign on IE 9 until they are fixed.
> Excluding failing tests on IE 9

- src/aria/widgets/form/DatePicker.js
- src/aria/widgets/form/DropDownTextInput.js
- src/aria/widgets/form/SelectBox.js
- test/aria/widgets/wai/dropdown/disabled/DropDownDynamicallyDisabledDownJawsTestCase.js
- test/aria/widgets/wai/dropdown/disabled/DropDownDynamicallyDisabledTabJawsTestCase.js
- test/aria/widgets/wai/dropdown/disabled/DropDownInitiallyDisabledDownJawsTestCase.js
- test/aria/widgets/wai/dropdown/disabled/DropDownInitiallyDisabledTabJawsTestCase.js
- test/aria/widgets/wai/dropdown/disabled/Tpl.tpl
- test/aria/widgets/wai/dropdown/disabled/TplScript.js
This PR removes the "tabindex" attribute and adds the "aria-hidden" attribute on the dropdown icon of widgets when they are disabled.
> Dropdown icons no longer focusable when the widget is disabled

- .travis.yml
- src/aria/widgets/CfgBeans.js
- src/aria/widgets/form/DatePicker.js
- src/aria/widgets/form/DropDownListTrait.js
- src/aria/widgets/form/DropDownTextInput.js
- src/aria/widgets/form/DropDownTrait.js
- src/aria/widgets/form/Select.js
- src/aria/widgets/form/list/templates/ListTemplateScript.js
- test/aria/widgets/form/select/onBlur/SelectOnBlur.tpl
- test/aria/widgets/form/select/onBlur/SelectOnBlurRobotBase.js
- test/aria/widgets/form/select/onBlur/SelectOnBlurScript.js
- test/aria/widgets/form/select/onBlur/SelectOnBlurSimpleRobotTestCase.js
- test/aria/widgets/form/select/onBlur/SelectOnBlurStdRobotTestCase.js
- test/testConfigBuilder.js
This commit also adds some fixes to make sure there is no blur event when clicking on the dropdown icon or when clicking on an option in the list.
> Adding the onblur event on the Select widget

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/errorlist/ErrorList.js
- src/aria/widgets/errorlist/ErrorListController.js
- test/aria/widgets/errorlist/displayOptions/ErrorListCustomTemplate.tpl
- test/aria/widgets/errorlist/displayOptions/ErrorListDisplayOptionsTestCase.js
- test/aria/widgets/errorlist/displayOptions/Tpl.tpl
Now the template used by the `ErrorList` widget will have a `displayOptions` property in its data model, as defined by the user inside the widget instance's configuration under the homonym property.
> feat #1751 ErrorList widget: now custom displayOptions can be passed to the template

- test/aria/widgets/errorlist/displayOptions/ErrorListDisplayOptionsTestCase.js
This was an unnecessary double check, which moreover was not properly implemented to work in IE8.
> fix/test #1752 Removed unnecessary assert in test.aria.widgets.errorlist.displayOptions.ErrorListDisplayOptionsTestCase

- test/aria/widgets/form/autocomplete/issue315/OpenDropDownFromButtonRobotTestCase.js
- test/testConfigBuilder.js
This PR fixes test issues which are happening following commit 8432f5b24f516bfc1361181d98535736c5b9fd47 from #1749:
- `SelectOnBlurSimpleRobotTestCase` fails on Safari because a `<select>` in Safari (on Mac) behaves differently than in other browsers (on Windows): pressing the down arrow key opens the dropdown instead of only changing the selection, as it is expected in the test. This test is now excluded from the test campaign for Safari.
- `OpenDropDownFromButtonTestCase` fails on IE 8 because SynEvents does not faithfully reproduces the behavior of IE 8. This test was replaced by a robot test which correctly tests what is really happening on IE 8.
> Fixing issues in tests following #1749

- build/config/locales.json
- src/aria/resources/DateRes_ro_RO.js
This PR adds partial support for the Romanian language, which can be used to make `aria.utils.Date.format` return formatted dates in Romanian.
> Adding Romanian date resources

- src/aria/utils/Json.js
Fix for issue 1754
__includePropForBackRef now checks that the provided property name starts with, and not is equal to, the aria:listener and aria:reclistener prefixes.
> Fix for 1754 - fix __includePropForBackRef in utils/Json.js

- src/aria/jsunit/Assert.js
- src/aria/utils/Json.js
- test/aria/utils/JsonTestCase.js
Hi, I would like to propose this change. The issue that this is trying to address is when using the this.assertJsonEquals method in the attester test cases, if the objects are large, then the output is very difficult to debug, as the entire objects are printed out. With this change, only the differences between the objects will be logged, meaning easier debugging. How this has been done is to add a new generic diff method to aria.utils.Json (with test cases provided, and detailed comments on this method), and then to update the Assert.js' assertJsonEquals method to use it.
> aria.utils.Json.diff and update to the Assert.assertJsonEquals method

- src/aria/core/Cache.js
- src/aria/core/ClassMgr.js
- src/aria/core/Log.js
- src/aria/jsunit/Assert.js
- src/aria/jsunit/TestSuite.js
- test/aria/pageEngine/IframeBase.js
- test/aria/templates/inheritance/logs/LogsTestCase.js
- test/aria/utils/HistoryTestCase.js
- test/aria/widgets/form/autocomplete/issue315/OpenDropDownFromButtonRobotTestCase.js
Before this PR, creating an instance of `aria.jsunit.Assert` (the base class for most tests) cleared all appenders in `aria.core.Log`. Now, this class only manages its own appender to collect errors during tests and no longer impacts any other appender.
See also #590.
Also, a second commit in the PR removes the deprecation messages for `unloadClass` and `getFilename` as those methods are used in the framework itself (especially in base test classes but also in some other places) and the messages can then be confusing for an application developer which does not call those methods directly, and those messages are more visible in test logs if appenders are not cleared (and they are no longer cleared in the `Assert` class).
> Keep existing log appenders in aria.jsunit.Assert

- build/grunt-config/config-atpackager-prod.js
- package.json
- src/aria/core/JsonTypesCheck.js
- src/aria/core/JsonValidator.js
- src/aria/utils/BeanExtractor.js
- tasks/easypackage/configuration.js
- tasks/task-atbuild.js
- tasks/task-easypackage.js
- test/node/gruntTasks.js
- test/nodeTestResources/testProject/attester/attester3.yml
- test/nodeTestResources/testProject/attester/attester4.yml
- test/nodeTestResources/testProject/gruntfiles/Gruntfile4.js
- test/nodeTestResources/testProject/src/app/SampleBean.js
- test/nodeTestResources/testProject/test/SampleBeanTest.js
This PR adds support for beans pre-compilation and optimizes a bit `aria.core.JsonValidator` to avoid generating twice the same fast-normalization function when a bean can simply reuse the fast-normalization function of its parent.
> Beans pre-compilation

- build/grunt-config/config-atpackager-prod.js
- src/aria/Aria.js
- src/aria/core/BaseTypes.js
- src/aria/core/JsonTypesCheck.js
- src/aria/core/JsonValidator.js
- src/aria/utils/BeanExtractor.js
- test/nodeTestResources/testProject/attester/attester4.yml
- test/nodeTestResources/testProject/src/app/SampleBean.js
- test/nodeTestResources/testProject/test/SampleBeanTest.js
This PR contains a set of fixes and improvements linked to beans pre-compilation, introduced in #1759:
- the `ATDebug` flag when compiling beans is now removed because it also caused all templates to be compiled in debug mode (with line numbers)
- there are new checks in `BeanExtractor` to be sure that the configuration in the `JsonValidator` is correct for the extraction with the given options to be successful
- an issue with default values which were not correctly normalized in non debug mode is now fixed
- the value returned by the generated `$getDefault` functions is no longer fully normalized, but it is expanded in `$fastNorm` in order to reduce the size of compiled beans
- beans which are not used in the fast normalization process are now discarded by the bean extractor when …
> Fixes and improvements for beans pre-compilation

- src/aria/widgets/Widget.js
- src/aria/widgets/action/Button.js
- test/aria/widgets/wai/input/actionWidget/buttonTooltip/ButtonTooltipJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/buttonTooltip/ButtonTooltipJawsTestCaseTpl.tpl
This PR fixes an issue with the aria:Button widget with screen readers: the fact that the title attribute was not set on the button tag but on the containing span was preventing Jaws from reading the tooltip.
> fix aria:Button had its title attribute on the span instead of button

- test/testConfigBuilder.js
The following tests are now excluded from the test campaign because they often fail (those tests should be rewritten in a more reliable way):
on Firefox 3:
test.aria.utils.HistoryTestCase on Firefox 3
on IE 11 with JAWS:
test.aria.widgets.wai.errorlist.binding.ErrorListBindingJawsTestCase
> Excluding failing tests from campaign

- build/config/locales.json
- src/aria/resources/DateRes_sk_SK.js
This PR adds partial support for the Slovak language, which can be used to make aria.utils.Date.format return formatted dates in Slovak.
cf #1756 for the last added language (date resources only)
> Adding Slovak date resources

- src/aria/widgets/container/Dialog.js
- test/aria/widgets/container/dialog/movableResizableRaceCondition/DialogRaceCondition.tpl
- test/aria/widgets/container/dialog/movableResizableRaceCondition/DialogRaceConditionTestCase.js
Errors could happen in case a resizable or movable aria:Dialog is opened and immediately closed (and maybe re-opened) before some classes (i.e. aria.utils.resize.Resize or aria.utils.dragdrop.Drag) are fully loaded.
> fix race condition when opening a resizable or movable dialog

- src/aria/jsunit/TemplateTestCase.js
- test/aria/jsunit/templateTests/TemplateTestCaseTemplateExtraOptionsTestCase.js
- test/aria/jsunit/templateTests/TemplateTestCaseTemplateExtraOptionsTestCaseTpl.tpl
- test/aria/jsunit/templateTests/TemplateTestCaseTemplateExtraOptionsTestCaseTplScript.js
Any option not already set (by other `env` properties or else) will be taken into account from the object set in `env.templateLoadingExtraOptions`; in other words those options have the least precedence.
> feat/test #1763 Now in TemplateTestCase it is possible to pass any option to the underlying Aria.loadTemplate call

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/errorlist/ErrorList.js
- test/aria/widgets/wai/errorlist/binding/ErrorListBindingCtrl.js
- test/aria/widgets/wai/errorlist/binding/ErrorListBindingTpl.tpl
- test/aria/widgets/wai/errorlist/binding/ErrorListNoAriaLiveJawsTestCase.js
This new `ariaLive` parameter allows to specify whether `role="alert"` and `aria-live="assertive"` are included (`true`) or omitted (`false`) on the container element of the `@aria:ErrorList` widget (defaults to `true`, only used if `waiAria` is `true`)
> New `ariaLive` parameter on the `@aria:ErrorList` widget

- build/config/locales.json
- src/aria/resources/DateRes_bg_BG.js
This commit adds partial support for the Bulgarian language, which can be used to make aria.utils.Date.format return formatted dates in Bulgarian.
cf #1767 for the last added language (date resources only)
> Adding Bulgarian date resources

- build/config/locales.json
- src/aria/resources/DateRes_mn_MN.js
This commit adds partial support for the Mongolian language, which can be used to make `aria.utils.Date.format` return formatted dates in Mongolian.
cf #1771 for the last added language (date resources only)
> Adding Mongolian date resources

- src/aria/utils/Dom.js
In Chrome 61, as specified in https://blog.chromium.org/2017/08/chrome-61-beta-javascript-modules.html:
> To align with the spec and preserve browser consistency, the scrollingElement is now the documentElement in standards mode.
This commit fixes the problems caused by this change in Chrome 61 by first using `document.scrollingElement` before relying on a browser-dependent logic to determine which is the scrolling element.
This commit fixes `test.aria.utils.DomScrollIntoViewTestCase` (and probably other tests too) on Chrome 61.
> Chrome 61 has document.scrollingElement = document.documentElement

- src/aria/resources/DateRes_vi_VN.js
> fix #1783 Wrong wording for "Saturday" in Vietnamese language

- src/aria/utils/overlay/Overlay.js
- test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/asDescendant/IndexTestCase.js
This commit fixes a regression caused by commit 45f686eaa6e018b6eaa4b91db74a774b20b65028, by uncommenting the code already written by @ymeine to take into account child elements when computing the z-index to apply on an element.
> fix overlay z-index computation (now takes child elements into account)

- .travis.yml
- test/testConfigBuilder.js
It seems that the `awesome` package raises random issues while being installed (cf https://travis-ci.org/ariatemplates/ariatemplates/builds/309427769 and https://travis-ci.org/divdavem/ariatemplates/builds/309427661 one installation is failing, the other is successful, both from the same commit).
Let's remove it and disable the test that depends on it to make our build more reliable (also, that test was not always working reliably).
> fixing issue while installing "awesome" on travis-ci

- src/aria/widgets/CfgBeans.js
- src/aria/widgets/container/Dialog.js
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreDisabledRobotTestCase.js
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreEnabledRobotTestCase.js
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreEventuallyDisabledRobotTestCase.js
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreEventuallyEnabledRobotTestCase.js
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreFocusOnClose.tpl
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreFocusOnCloseRobotBase.js
- test/aria/widgets/container/dialog/restoreFocusOnClose/RestoreFocusOnCloseScript.js
- test/testConfigBuilder.js
This commit adds the "restoreFocusOnClose" parameter on the Dialog widget, which is true by default (to keep the same behavior as before which restores the focus to the element that was focused before the dialog was opened when the dialog is closed) but which can now also be set to false (either directly in the configuration, or through a binding) to disable the automatic restoration of the focus. This is especially useful if the application manages the focus itself when the dialog is closed and does not want the framework to interfere.
This parameter is ignored for non-modal dialogs (the focus is never restored in that case).
> Adding restoreFocusOnClose parameter in Dialog widget

- src/aria/jsunit/JawsTestCase.js
- src/aria/widgets/CfgBeans.js
- src/aria/widgets/action/Button.js
- test/aria/widgets/wai/input/actionWidget/blurBeforeAction/BlurBeforeActionJawsTestCase.js
- test/aria/widgets/wai/input/actionWidget/blurBeforeAction/BlurBeforeActionTpl.tpl
- test/aria/widgets/wai/input/actionWidget/blurBeforeAction/BlurBeforeActionTplScript.js
If `blurBeforeAction` is `true`, the button blurs any other focused element on the page before calling the `onclick` handler.
This is especially useful to solve issues with screen readers (such as JAWS) that can click on a button without changing the focus, and if the focus is still in a field, the data model may contain an old value because the value is usually only updated in the data model on blur.
> Adding blurBeforeAction option in aria:Button configuration 

- src/aria/utils/Dom.js
- src/aria/widgets/form/DropDownTrait.js
- src/aria/widgets/form/MultiSelect.js
- test/aria/widgets/wai/dropdown/dialogTitle/DropDownDialogTitleJawsTestCase.js
- test/aria/widgets/wai/dropdown/dialogTitle/Tpl.tpl
- test/aria/widgets/wai/dropdown/dialogTitle/TplScript.js
This PR contains a workaround for an issue with the JAWS screen reader: JAWS reads the dialog title when closing a dropdown widget that is inside the dialog, whereas it should not.
As investigated by @ymeine:
> - the issue comes from the fact the dropdown's element is physically outside the dialog, the focus is moved to it, and when closing the dropdown the focus is put back to the dialog, making JAWS announce it again
> - we can't put the dropdown's element inside the dialog because of other limitations (possible overflow styling on parent elements)
> - the right way to do is to use the WAI-ARIA attribute `aria-owns` to restore the logical structure of elements but JAWS doesn't support it
> - the workaround is to remove the `role=dialog` attribute on the Dialog's root element as long as …
> fix JAWS reading dialog title when closing dropdown widget

- build/grunt-config/config-atpackager-bootstrap.js
- src/aria-tester.html
This allows to publish to production the full `aria` folder without having to filter files inside it.
> Moving aria/tester/index.html to aria-tester.html

- test/aria/widgets/container/dialog/movable/test5/MovableDialogFiveRobotTestCase.js
- test/aria/widgets/container/dialog/resize/test4/DialogOnResizeScrollRobotTestCase.js
- test/aria/widgets/container/dialog/resize/test5/OverlayOnResizeScrollRobotTestCase.js
This PR fixes some tests that were not working properly when run with a large viewport because the viewport was able to fully display the content and the tests were expecting the viewport to have a scrollbar.
This commit fixes this by increasing the size of the content to make sure that a scrollbar is present.
> fix/test Fixing tests not working properly with large viewport

- src/aria/utils/Date.js
- src/aria/widgets/calendar/CalendarController.js
- test/aria/utils/DateTestCase.js
The calendar widget now uses `aria.utils.Date.getWeekNumber` (which is compliant with standard rules) to compute the week number, instead of considering that the first week of the year is the first full week.
For example, in 2019, if the first day of the week is Monday, week 1 should start on 31/12/2018 and not on 07/01/2019.
This commit extends `aria.utils.Date.getWeekNumber` to allow any day of the week to be specified as the first day of the week.
If Monday is selected, rules from ISO 8601 are applied (the first week of the year is the week containing January 4th).
Otherwise, the first week of the year is the week containing January 1st.
> Wrong week numbers displayed in aria:Calendar (and aria:DatePicker)

- src/aria/widgets/form/AutoComplete.js
- test/testConfigBuilder.js
This fixes an issue with JAWS, which reads the previously focused autocomplete field when pressing tab while the suggestions list is opened.
The problem seems to come from the `aria-activedescendant` attribute being removed too quickly (before the next field is focused).
> Screen reader reading previously focused autocomplete field on tab

- src/aria/DomEvent.js
Firefox 66 and above has standardized their keyCodes for events, this needs to be reflected in a change to the DomEvent which doesn't perform some normalization of the keyCodes for Gecko browsers. Now a change is needed to not do this check only for Gecko version less than 66
> DomEvent change to reflect a change in Firefox from version 66 and above

- test/testConfigBuilder.js
This PR excludes Issue353RobotTestCase from the set of tests run by PhantomJS which makes it run by Firefox in Travis.
> fix/test Issue353RobotTestCase randomly failing on PhantomJS

- test/testConfigBuilder.js
IE 9 and Firefox 11 are no longer supported by the Google Maps JS API.
cf https://developers.google.com/maps/documentation/javascript/browsersupport
The following exception is raised on unsupported browsers when running
this test:
"Error: The Google Maps JavaScript API does not support this browser."
> fix/test: Excluding Google3MapProviderTestCase on IE 9 and Firefox 11

- test/aria/widgets/container/dialog/resize/dontSelectOnResize/DialogResizeDontSelectRobotTestCase.js
With Microsoft EdgeHTML (at least version 18.17763), the text selection with the robot has an issue with DialogResizeDontSelectRobotTestCase (it selects much more than expected).
This PR disables text selection check in this case.
> fix/test: DialogResizeDontSelectRobotTestCase on Microsoft Edge

- src/aria/map/providers/Microsoft8MapProvider.js
- test/aria/map/MapManagerTwoBisTestCase.js
- test/aria/map/MapManagerTwoTestCase.js
Bing maps is not supposed to be used without a key, and it even fails displaying a proper error message in that case.
This commit adds a default invalid key for quick tests allowing usage of the map in case a key is not provided as it should.
> Add a default invalid key for Bing maps

- src/aria/utils/validators/MinMaxLength.js
- test/aria/utils/validators/MinMaxLengthTestCase.js
The previous message could give the impression that the boundaries were strict (> and <) but they are not (>= and <=).
> Improving the default error message for the MinMaxLength validator

- src/aria/widgets/container/Tab.js
- test/aria/widgets/container/tab/dontFocusTab/DontFocusTabRobotTestCase.js
- test/aria/widgets/container/tab/dontFocusTab/DontFocusTabRobotTestCaseTpl.tpl
Clicking on `<td>` or `<span style="display:inline-block">` elements on IE focuses those elements whereas they are not focusable on other browsers (when `tabindex` is not specified).
This fix prevents this discrepancy between browsers from happening for the aria:Tab widget.
> fix incorrect focus state in IE for aria:Tab widget

- src/aria/utils/overlay/LoadingOverlay.js
- test/aria/utils/overlay/loadingIndicator/wai/body/BodyOverlayJawsTestCase.js
- test/aria/utils/overlay/loadingIndicator/wai/body/BodyOverlayJawsTestCaseTpl.tpl
- test/aria/utils/overlay/loadingIndicator/wai/body/BodyOverlayJawsTestCaseTplScript.js
Creating a loading overlay on the body added aria-hidden=true on the body which prevented Jaws 2021 (with Edge) from reading the text.
> Jaws 2021 with Edge not reading loading overlay text

- src/aria/widgets/form/DropDownTextInput.js
This commit enables the role="button" attribute on MultiSelect widget, so that MultiSelect icons will be included in the list of
buttons displayed by screen readers and become focusable by tab.
> fix: Enabling role=button for multiselect widgets
