src/aria/utils/Size.js
test/aria/widgets/form/autocomplete/AutoCompleteTestSuite.js
test/aria/widgets/form/autocomplete/popupWidth/AIRList.tpl
test/aria/widgets/form/autocomplete/popupWidth/AIRListScript.js
test/aria/widgets/form/autocomplete/popupWidth/AdaptToContentWidthTest.js
test/aria/widgets/form/autocomplete/popupWidth/AdaptToContentWidthTpl.tpl
test/aria/widgets/form/autocomplete/popupWidth/AdaptToContentWidthTplScript.js
test/aria/widgets/form/autocomplete/popupWidth/CustomResourceHandler.js

Method `aria.utils.Size.setContrains` was not correctly taking into account the presence of a vertical scrollbar when the haight of the element is bigger than the maximum one allowed.

Dropdown free size was comupted incorrectly in case of vertical scrollbars

---

build/config/locales.json
src/aria/resources/CalendarRes_ms_MY.js
src/aria/resources/DateRes_ms_MY.js
src/aria/resources/multiselect/FooterRes_ms_MY.js

locales.json modified with Malay entry created and resource files added

Addition of resources for Malay language

---

package.json
test/aria/templates/TemplatesTestSuite.js
test/aria/templates/robotCalibrationTest/RobotCalibrationTest.js
test/aria/templates/robotCalibrationTest/RobotCalibrationTestTpl.tpl

Adding a test to check the calibration of the robot

---

build/config/locales.json
src/aria/resources/CalendarRes_cs_CZ.js
src/aria/resources/DateRes_cs_CZ.js
src/aria/resources/multiselect/FooterRes_cs_CZ.js

Cf pull requests for previous languages: #1422, #1318, #1050, #935

Addition of resources for Czech language (cs_CZ)

---

test/aria/templates/resources/TemplateWithResourcesTestCase.js

This commit fixes the TemplateWithResourcesTestCase test when it is run with devMode = true.

fix test.aria.templates.resources.TemplateWithResourcesTestCase

---

.travis.yml

This switches to the container-based infrastructure on travis
cf http://docs.travis-ci.com/user/migrating-from-legacy/

Using sudo:false in .travis.yml

---

package.json
test/node/gruntTasks.js
test/node/npm_start.js
test/node/util/fork.js

Cf the following failure:
- https://travis-ci.org/divdavem/ariatemplates/builds/87682938

Fixing mocha tests and improving logs

---

src/aria/tester/runner/view/BaseCSS.tpl.css
src/aria/tester/runner/view/filter/FilterCSS.tpl.css
src/aria/tester/runner/view/header/HeaderCSS.tpl.css
src/aria/utils/Dom.js
src/aria/widgets/GlobalStyle.tpl.css
src/aria/widgets/action/Button.js

The behavior in Opera is very close to the one of Chrome as both browsers have much code in common.

Adding isOpera whenever there is isChrome

---

src/aria/popups/PopupManager.js

This is needed in case several popup managers need to cooperate, so that another popup manager can display a modal dialog above an Aria Templates modal dialog.

Now raising an event when preventing the focus because of a modal dialog

---

src/aria/css/atskin.js
src/aria/widgets/CfgBeans.js
src/aria/widgets/container/Tab.js
src/aria/widgets/container/TabPanel.js
test/EnhancedJawsTestCase.js
test/EnhancedRobotTestCase.js
test/JawsTestSuite.js
test/aria/widgets/wai/WaiTestSuite.js
test/aria/widgets/wai/popup/dialog/modal/ModalDialogJawsTest.js
test/aria/widgets/wai/tabs/Base.js
test/aria/widgets/wai/tabs/Group1.js
test/aria/widgets/wai/tabs/Group2.js
test/aria/widgets/wai/tabs/Group3.js
test/aria/widgets/wai/tabs/Group4.js
test/aria/widgets/wai/tabs/Model.js
test/aria/widgets/wai/tabs/Suite.js
test/aria/widgets/wai/tabs/TabsJawsTest.js
test/aria/widgets/wai/tabs/Tpl.tpl
test/aria/widgets/wai/tabs/TplCSS.tpl.css

Features:
- attributes
- `role`: `"tab"` and `"tabpanel"`
- `aria-controls`: the `Tab` holds the id of the controlled `TabPanel`
- `aria-labelledby`: the `TabPanel` refers to the id of the Tab to be used as a label
- `aria-selected`, `aria-expanded`: set to `"true"` on the currently selected `Tab`, `"false"` on the others
- `aria-disabled`: for disabled `Tab`s
- navigation
- Tab can be selected using <kbd>space</kbd>
Remaining:
- navigation using arrow keys

feat WAI-ARIA - Tab and TabPanel

---

src/aria/widgets/CfgBeans.js
src/aria/widgets/form/AutoComplete.js
src/aria/widgets/form/DropDownListTrait.js
src/aria/widgets/form/SelectBox.js
test/JawsTestSuite.js
test/aria/widgets/wai/input/selectBox/SelectBoxSuggestionsJawsTestCase.js
test/aria/widgets/wai/input/selectBox/SelectBoxSuggestionsJawsTestCaseTpl.tpl

In the SelectBox, when there are suggestions Jaws doesn't announce that there are suggestions.  Should work in the same way as the AutoComplete, for example if there are 3 items in the list Jaws should say "There are 3 suggestions".

feat WAI-ARIA fixes an issue with the SelectBox where the list of results is not announced by JAWS

---

src/aria/widgets/CfgBeans.js
src/aria/widgets/form/AutoComplete.js
src/aria/widgets/form/DatePicker.js
src/aria/widgets/form/DropDownTextInput.js
src/aria/widgets/form/MultiSelect.js
src/aria/widgets/form/SelectBox.js
test/JawsTestSuite.js
test/aria/widgets/wai/iconLabel/IconLabelJawsTest.js
test/aria/widgets/wai/iconLabel/IconLabelTpl.tpl
test/aria/widgets/wai/iconLabel/IconLabelTplScript.js

feat add waiIconLabel to enable aria-label on widget with expand button

---

test/aria/widgets/wai/errorlist/binding/ErrorListBindingJawsTestCase.js

This commit fixes `test.aria.widgets.wai.errorlist.binding.ErrorListBindingJawsTestCase` after the changes introduced by 5086dc94fa6833052cd63804f5685982ee79074c.

Fixing ErrorListBindingJawsTestCase

---

scripts/attest.js

Useful to just un-comment these options when required in dev mode

feat Add commented options in attester

---

src/aria/popups/Popup.js
src/aria/popups/PopupManager.js
src/aria/popups/PopupNavigationManager.js
src/aria/templates/NavigationManager.js
src/aria/widgets/Icon.js
test/EnhancedRobotTestCase.js
test/aria/widgets/wai/popup/dialog/modal/Base.js
test/aria/widgets/wai/popup/dialog/modal/Model.js
test/aria/widgets/wai/popup/dialog/modal/Tpl.tpl

Now the focus is maintained inside the popup when navigating with the tab key.
This will loop through the elements of the popup, taking into account forward and backward navigation.
This will also handle properly the focus and the navigation direction when navigating from the user agent GUI.
PTR 11592232
AT-1425
AT-1442
AT-1455

feat #1654 WAI-ARIA - Modal dialog - Focus cycling for accessible modal popups

---

src/aria/widgets/form/DropDownTrait.js
src/aria/widgets/form/MultiSelect.js
test/aria/widgets/wai/multiselect/MultiSelectJawsTest.js
test/aria/widgets/wai/multiselect/MultiSelectTpl.tpl

It includes these changes:
- The icon is now focusable
- role="combobox" is removed for a better reading
AT-1449

fix Multiselect enhancement for JAWS

---

test/aria/widgets/wai/iconLabel/IconLabelJawsTest.js

This PR fixes test.aria.widgets.wai.iconLabel.IconLabelJawsTest after some changes in the multiselect.

fix/test test.aria.widgets.wai.iconLabel.IconLabelJawsTest

---

test/aria/widgets/wai/input/label/MultiSelectJawsTestCase.js

This PR fixes test.aria.widgets.wai.input.label.MultiSelectJawsTestCase after changes in the MultiSelect.

fix test.aria.widgets.wai.input.label.MultiSelectJawsTestCase

---

src/aria/popups/PopupNavigationManager.js
src/aria/widgets/CfgBeans.js
src/aria/widgets/action/LinkStyle.tpl.css
src/aria/widgets/form/CheckBox.js
src/aria/widgets/form/MultiSelect.js
src/aria/widgets/form/list/IListController.js
src/aria/widgets/form/list/ListController.js
src/aria/widgets/form/templates/TemplateMultiSelect.tpl
src/aria/widgets/form/templates/TemplateMultiSelectScript.js
test/aria/widgets/wai/multiselect/MultiSelectTabJawsTest.js
test/aria/widgets/wai/multiselect/MultiSelectTpl.tpl

fix keyboard navigation issues with the multiselect

---

src/aria/jsunit/TestRunner.js
test/aria/widgets/wai/tabs/TabsJawsTest.js

The test has been updated to match the new behavior of the two widgets Tab and TabPanel.

fix/test #1672 test.aria.widgets.wai.tabs.TabsJawsTest to match the latest behavior changes

---

src/aria/jsunit/TestRunner.js
test/aria/widgets/wai/errorlist/binding/ErrorListBindingJawsTestCase.js
test/aria/widgets/wai/tabs/TabsJawsTest.js

The expected history was not correct.

fix/test #1673 test.aria.widgets.wai.errorlist.binding.ErrorListBindingJawsTestCase had wrong expected history

---

src/aria/widgets/CfgBeans.js
src/aria/widgets/action/ActionWidget.js
src/aria/widgets/action/Link.js
src/aria/widgets/controllers/DateController.js
src/aria/widgets/form/DatePicker.js
test/EnhancedJawsTestCase.js
test/JawsTestSuite.js
test/aria/widgets/wai/datePicker/readDate/CSS.tpl.css
test/aria/widgets/wai/datePicker/readDate/DatePickerReadDateJawsTestCase.js
test/aria/widgets/wai/datePicker/readDate/Tpl.tpl
test/aria/widgets/wai/datePicker/readDate/TplScript.js
test/aria/widgets/wai/input/actionWidget/Base.js

Now when the user inputs a date, be it from the calendar or when typing in, if the date is valid it is read by the screen reader following a provided format: waiAriaConfirmDateFormat (which defaults to waiAriaDateFormat or a long date format).
When the user types the text in, a debouncing algorithm is applied, which is controlled by a delay waiAriaConfirmDateDelay, defaulting to 50 ms.
References:
- AT-1509

feat #1677 WAI-ARIA - DatePicker - Reading the input date when valid

---

test/EnhancedJawsTestCase.js
test/JawsTestSuite.js
test/aria/widgets/wai/datePicker/readDate/DatePickerReadDateJawsTestCase.js
test/aria/widgets/wai/input/actionWidget/Base.js
test/aria/widgets/wai/input/actionWidget/ButtonJawsTestCase.js
test/aria/widgets/wai/input/actionWidget/IconButtonJawsTestCase.js
test/aria/widgets/wai/input/actionWidget/InputActionWidgetJawsTestSuite.js
test/aria/widgets/wai/input/actionWidget/LinkJawsTestCase.js
test/aria/widgets/wai/input/actionWidget/SimpleButtonJawsTestCase.js
test/aria/widgets/wai/input/actionWidget/SortIndicatorJawsTestCase.js
test/aria/widgets/wai/popup/dialog/modal/PopupDialogModalJawsTestCase.js
test/aria/widgets/wai/tabs/TabsJawsTestCase.js
test/aria/widgets/wai/tabs/update1/TabsUpdate1JawsTestCase.js

Renamed test classes to match conventions, and added missing tests to the Jaws test suite.
Also improved utilities for Jaws tests (EnhancedJawsTestCase), and simplified the tests using it.

Added some missing Jaws tests, ensured naming conventions and improved code

---

src/aria/widgets/form/TextInput.js
test/aria/widgets/autoselect/tab/NoAutoSelectTabRobotTestCase.js
test/aria/widgets/autoselect/tab/NoAutoSelectTabRobotTestCaseTpl.tpl
test/aria/widgets/autoselect/tab/NoAutoSelectTabRobotTestCaseTplScript.js

fix Some widgets were not autoselected when using the tab key

---

src/aria/utils/DomNavigationManager.js
test/aria/utils/domNavigationManager/CSS.tpl.css
test/aria/utils/domNavigationManager/DomNavigationManagerJawsTestCase.js
test/aria/utils/domNavigationManager/DomNavigationManagerRobotTestCase.js

Because of various API or syntax incompatibilities.

fix #1709 Fixed aria.utils.DomNavigationManager for IE 7, 8, 9

---

package.json
test/testConfigBuilder.js

This commit creates a list of failing tests (for each browser), which will be excluded during the release campaign until they are individually investigated and fixed.

Excluding failing tests

---

src/aria/templates/CfgBeans.js
src/aria/templates/DomElementWrapper.js
src/aria/templates/Section.js
src/aria/utils/Accessibility.js
src/aria/utils/DomOverlay.js
src/aria/utils/overlay/LoadingOverlay.js
src/aria/utils/overlay/Overlay.js
src/aria/widgets/Widget.js
test/aria/utils/accessibility/AccessibilityJawsTestCase.js
test/aria/utils/accessibility/Tpl.tpl
test/aria/widgets/wai/processingIndicator/Css.tpl.css
test/aria/widgets/wai/processingIndicator/ProcessingIndicatorJawsTestCase.js
test/aria/widgets/wai/processingIndicator/Tpl.tpl
test/aria/widgets/wai/processingIndicator/TplScript.js

Now processing indicators - on elements and sections - can be accessible, the loading message being repeated every X seconds (by default 2) and the elements under the indicator being hidden the time it is active.
AT-1540

feat #1723 WAI-ARIA - Processing Indicator - Implement processing indicators

---

src/aria/widgets/container/Dialog.js
test/aria/widgets/container/dialog/resize/noRefresh/ResizableDialogRobotTestCase.js
test/aria/widgets/container/dialog/resize/noRefresh/ResizableDialogTemplate.tpl
test/aria/widgets/container/dialog/resize/noRefresh/page1.html
test/aria/widgets/container/dialog/resize/noRefresh/page2.html

This PR removes the refresh which happens after resizing a dialog.

Avoid refreshing dialog content after a resize

---

test/aria/templates/binding/recursiveBindingLeak/RecursiveBindingLeakTestCase.js
test/aria/templates/binding/recursiveBindingLeak/RecursiveBindingLeakTestCaseTpl.tpl
test/aria/templates/binding/recursiveBindingLeak/RecursiveBindingLeakTestCaseTplScript.js

This PR adds a test for #1755.

feat/test Adding test for #1755

---

src/aria/utils/overlay/Overlay.js
test/aria/templates/section/processingIndicator/ProcessingIndicatorOnSectionTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/IndexTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/IndexTestCaseTpl.tpl
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/ZIndexNewAlgorithmTestBase.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/ZIndexNewAlgorithmTestCSSBase.tpl.css
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/ZIndexNewAlgorithmTestTplBase.tpl
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/ZIndexNewAlgorithmTestTplBaseScript.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/asDescendant/IndexTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/asDescendant/IndexTestCaseTpl.tpl
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/asNestedParent/IndexTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/asNestedParent/IndexTestCaseTpl.tpl
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/opacity/IndexTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/newStackingContext/opacity/IndexTestCaseTpl.tpl
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/noStackingContext/bare/IndexTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/noStackingContext/bare/IndexTestCaseTpl.tpl
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/noStackingContext/zIndexOnly/IndexTestCase.js
test/aria/utils/overlay/loadingIndicator/zindex/newAlgorithm/noStackingContext/zIndexOnly/IndexTestCaseTpl.tpl
test/aria/widgets/container/dialog/MovableDialogRobotBase.js
test/aria/widgets/container/dialog/indicators/DialogTestCase.js

The lesser the better for interoperability with other's code.
AT-1428
PTR 11674386

fix #1769 New algorithm to compute minimal (or no) z-index value for loading overlays

---

.travis.yml
package-lock.json
package.json

This PR updates dependencies used for tests on travis-ci.
Note that this PR supersedes #1772 (as the `package-lock.json` file is present)

Updating test dependencies

---

src/aria/utils/resize/Resize.js
test/EnhancedRobotBase.js
test/aria/widgets/container/dialog/resize/dontSelectOnResize/DialogResizeDontSelectRobotTestCase.js
test/aria/widgets/container/dialog/resize/dontSelectOnResize/DialogResizeDontSelectRobotTestCaseTpl.tpl
test/aria/widgets/container/dialog/resize/dontSelectOnResize/DialogResizeDontSelectRobotTestCaseTplScript.js
test/testConfigBuilder.js

fix #1777 Selection is prevented when dragging, but it was not enabled again properly when stopping the drag

---

.gitignore
package.json
scripts/browsersCampaigns.js
src/aria/widgets/form/DropDownTextInput.js
src/aria/widgets/form/DropDownTrait.js
src/aria/widgets/form/MultiAutoComplete.js
test/aria/widgets/form/selectbox/SelectboxRobotTestCase.js
test/testConfigBuilder.js

This PR fixes test.aria.widgets.form.selectbox.SelectboxTestCase on IE 11.

fix Selectbox issue with helptext on IE 11

---

src/aria/core/Interfaces.js

Fix: Invalid display of source files for interfaces wrapper 

---

test/aria/widgets/container/dialog/resize/test5/OverlayOnResizeScrollRobotTestCase.js

Adding a 1s delay (similar to 0d6af26edc56c97c36b1353add2e418f0261d731)

fix/test OverlayOnResizeScrollRobotTestCase

---

.travis.yml
README.md
build/grunt-config/config-atpackager-bootstrap.js
build/grunt-config/config-packaging.js
package-lock.json
package.json
scripts/browsersCampaigns.js
src/aria/jsunit/TemplateTestCase.js
src/aria/jsunit/TestCase.js
test/aria/pageEngine/IframeBase.js
test/testConfigBuilder.js

Note that this PR depends on the following other PRs:

Adding test coverage

---

src/aria/jsunit/SynEvents.js
test/aria/widgets/form/autocomplete/issue315/OpenDropDownFromButtonRobotTestCase.js

feat/test: Adding logs for the following robot actions: click, type, move, drag

---

src/aria/popups/PopupManager.js

fix scrolling inside a popup on iOS 12 and 13 does not work
